modules/parsoid/files/settings.js
will add localsettings setting also
=> add parsoid config for VE genwiki

modules/parsoid/files/settings.js
=> Add VE to unikumwiki

modules/icinga/files/contactgroups.cfg, modules/icinga/files/contacts.cfg
Not following abc order since irc was at bottom.
=> Add myself to icinga contacts

modules/parsoid/files/settings.js
=> Add parsoid for permanentfuturelabwiki

modules/icinga/files/contacts.cfg
Old one redieects to here, no point keeping it redirect. Make it send to the new one.
=> Change email address

modules/parsoid/files/settings.js
=> Remove cinemawiki

modules/parsoid/files/settings.js
Blocking miraheze/mw-config#192
=> Add parsoid for applebranchwiki

modules/parsoid/files/settings.js
Per request, to enable Flow/VE
=> Add parsoid to 8stationwiki

modules/postfix/files/aliases
add myself to stewards@ and sysadmin@
=> update mail aliases, remove john and add myself

modules/parsoid/files/settings.js
=> add adnovumwiki to parsoid (for Flow+VE)

modules/parsoid/files/settings.js
=> add parsoid to shoppingwiki for VE

modules/parsoid/files/settings.js
Companion to https://github.com/miraheze/mw-config/pull/284
=> Add parsoid to boulderwikiwiki

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/285
=> add parsoid to chandruswethswiki for VE

modules/parsoid/files/settings.js
for miraheze/mw-config/issues/289
=> add parsoid for cssandjsschoolboardwiki per VE

modules/parsoid/files/settings.js
Per miraheze/mw-config/issues/295
=> add parsoid for pflanzenwiki per VE

modules/users/data/data.yaml
working on security related things, real time testing and fine tuning necessary, x-service.
=> re-add johnflewis

modules/parsoid/files/settings.js
PER miraheze/mw-config/issues/298
=> add parsoid config for vrgo (VE)

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/310
=> add parsoid for urho3dwiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/315
=> add parsoid to aktposwiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/321
=> parsoid for luckandlogicwiki for VE

modules/parsoid/files/settings.js
It's been broken, but I think this should fix it.
=> Update parsoid for boulderwiki.org

modules/parsoid/files/settings.js
=> parsoid for weflowwiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/342
=> parsoid for testwiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/349
=> add parsoid for islamwissenschaftwiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/358
=> add taylorwiki parsoid for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/360
=> add parsoid config for VE hobbieswiki

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/363
=> add parsoid to elainarmuawiki for VE

modules/parsoid/files/settings.js
per miraheze/mw-config/issues/370
=> add parsoid to sirkotwiki for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/393
WIKI is included in name (wikiwiki)
=> add parsoid to drunkenpeasantswiki for VE and Flow

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/401
=> lclwikiwiki parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/404
=> newtrendwiki parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/413
=> add parsoid to hftqms for VE

modules/postfix/files/aliases
per [IRC](https://botbot.me/freenode/miraheze/2016-03-20/?msg=62543234&page=1).
=> Alias change for myself

modules/parsoid/manifests/init.pp
For the VE, requested in wiki creation request 709.
=> Add oyeavdelingenwiki for parsoid

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/428
=> add parsoid for VE to nidda23wiki

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/438
=> add VE for clementsworldbuilding for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/444
=> add parsoid for VE to ernaehrungsrathh

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/443
=> add parsoid for stellachronica for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/449
=> Add parsoid to foodsharinghamburg for VE

modules/parsoid/manifests/init.pp
=> Adding parsoid for littlebigplanet

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/462
=> add aacenterpriselearning to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/463
=> add parsoid for VE and Flow touhouengine

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/464
=> add parsoid for eva for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/466
=> add parsoid to datachron for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/471
=> add parsoid to alanpedia for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/473
=> snowthegame parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/475
=> tme parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/483
=> Parsoid for VE for yggdrasilwiki

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/484
=> priyo parsoid for VE

.github/ISSUE_TEMPLATE.md
As per miraheze/mw-config repo's .github/ISSUE_TEMPLATE.md.
=> Add .github/ISSUE_TEMPLATE.md for no issue warning

modules/parsoid/manifests/init.pp
=> Parsoid for VE for allbanks2wiki

modules/parsoid/manifests/init.pp
=> Turn on parsiod for lunfengwiki

modules/parsoid/manifests/init.pp
Enable parsoid for geirpediawiki for VE.
=> Enable parsoid for geirpediawiki

modules/parsoid/manifests/init.pp
=> Enable VE for neuronpediawiki

modules/parsoid/manifests/init.pp
=> Enable VE for maiasongcontestwiki

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/506
=> add parsoid to civitaswiki for VE

modules/users/data/data.yaml
heres to hoping this works since puttygen sucks trash
=> add new work key for ndkilla ssh

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/527
=> add parsoid for VE to musiclibrarywiki

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/532
=> add parsoid to inazumaeleven for VE

modules/parsoid/manifests/init.pp
=> add parsoid to ircwiki for VE and flow

modules/parsoid/manifests/init.pp
https://github.com/miraheze/mw-config/pull/559
=> parsoid for VE for yourosongcontest

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/560
=> add casuarina to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/576
=> add parsoid to gnc for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/579
=> add xdjibi to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/588
=> add 3dicxyz to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/594
=> add parsoid to frontdesks for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/600
=> add parsoid to videogameswiki for VE

modules/parsoid/manifests/init.pp
=> add parsoid to ageofimperialism for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/601
=> add parsoid to aurcusonline for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/615
=> add parsoid to robloxscripters for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/616
=> add parsoid to thehushhushsaga for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/614
=> add menufeed to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/620
=> add parsoid to rpcharacters for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/621
=> add youtube to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/634
=> add parsoid to justinbieberwiki for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/637
=> add opengovpioneers to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/643
=> add tcc6440 to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/641
=> add lingnlang to parsoid for VE

modules/parsoid/manifests/init.pp
Adding bmed to list of wikis per VE https://github.com/miraheze/mw-config/pull/651
=> Add bmed per VE

modules/parsoid/manifests/init.pp
=> Added starset wiki for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/659
=> add parsoid to detlefs for VE and Flow

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/667
=> add oncproject to parsoid for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/677
=> add parsoid to janesskillspack for VE

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/681
=> add espiral to parsoid for VE and flow

modules/parsoid/manifests/init.pp
per miraheze/mw-config/issues/689
=> add parsoid to wthsapgov for VE

modules/parsoid/manifests/init.pp
https://github.com/miraheze/mw-config/pull/841
=> Add fablabesds to parsoid

modules/parsoid/manifests/init.pp
per miraheze/mw-config/pull/893
=> enable parsoid (gzewiki) VE

modules/parsoid/manifests/init.pp
=> Added 'calexit' wiki to existing list

modules/mediawiki/templates/mediawiki.conf
Not sure if this will affect the custom domain, but submitting anyway. Please correct me if wrong.
Thanks for review anyway, Referenced commit d9adcf4042ac256c191ea5b4c1f77607a6bd41e0.
=> Add preload to HSTS

modules/postfix/files/aliases, modules/users/data/data.yaml
Well, I'm not a Jedi but anyway.
For mail aliases, I'm receiving address on two email addresses.
Disclaimer: I only watched Star Wars 7.
=> Return of the Jedi

modules/users/data/data.yaml
Proof of new key is at http://link.revi.xyz/2kjmNdj.
=> Add new ssh key for ssh user revi

modules/mediawiki/manifests/dumps.pp
Apparently the import thing isn't possible either so sticking with manual.
=> add icmscholarswiki and scruffywiki dumps + alphabetize

modules/phabricator/data/config.yaml
=> add IRC nickname option to Phab

modules/phabricator/data/config.yaml, modules/phabricator/files/apache.conf
Fixes [T1752](https://phabricator.miraheze.org/T1752). config for phab settings and apache to make server accept requests to alt-domain.
=> Set Phabricator alt domain

modules/role/manifests/redis.pp
See T613 comment, could reduce/fix login issues, not sure if this is the way to go though
=> slightly increase redis maxmemory

modules/mediawiki/manifests/dumps.pp
=> monthly backup for modularwiki per req T1865

modules/acme/files/ssl-certificate
=> add .key output to ssl

modules/postfix/files/aliases
I've switched the main receiving address few months ago. Reflecting this here now.
=> Fix my email address

modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/PrivateSettings.php
Ops need to generate one and add it to the file first, of course.
=> add Google Maps API key per T696

modules/postfix/files/aliases
=> alias typo

modules/mediawiki/manifests/dumps.pp
=> Revert "add missing days to weekly dumps"

modules/mediawiki/manifests/dumps.pp
=> Revert "nenawikiwiki weekly dumps"

modules/mediawiki/manifests/init.pp
There's probably some mistakes so needs review first.
@JohnFLewis
=> install HTMLDoc for PdfBook

modules/phabricator/files/phab.miraheze.wiki.conf
=> serve phab.miraheze.wiki .well-known reqs to mw1

modules/users/data/data.yaml
=> Revert "Reactivate shell account for Corey"

modules/icinga/files/contacts.cfg
Don't need recovery alerts, if there's an error I'll check it out more in depth anyway to see the source of the issue
=> remove recovery alerts for icinga for myself

modules/phabricator/data/config.yaml
Ref [T1934](https://phabricator.miraheze.org/T1934). Hush.
=> Uninstall unused phabricator applications

hieradata/common.yaml
[DO NOT merge unless you are upgrading]
=> switch branch to REL1_29

modules/mediawiki/manifests/dumps.pp
=> remove modularwiki dump

modules/mediawiki/manifests/dumps.pp
=> move scruffywiki dump to public

modules/mediawiki/manifests/dumps.pp
and also remove icmscholarswiki backup since it is only being backed up to my home dir which is pointless.
=> add lexiquewiki monthly backup

modules/postfix/files/aliases, modules/users/data/data.yaml
Ref T2191, Good luck!
Reducing ops onboarding stuff to just clicking merge button.
=> Promote Reception to ops

modules/icinga/files/contactgroups.cfg
=> add myself to ops icinga group

modules/mediawiki/manifests/dumps.pp
Per my request T2412. This is my first time actually changing the config itself so if there are any errors please point them out so I can rectify them :)
=> Adding TME XML dump

.github/ISSUE_REPLY_TEMPLATE.md
=> Add autoresponder

modules/postfix/files/aliases
=> Add wiki-abuse alias

modules/bacula/templates/director/bacula-dir.conf
=> increase backup sizes (mostly static)

modules/postfix/files/aliases
Per commission consensus. Ref [T2601](https://phabricator.miraheze.org/T2601).
=> Modify Code of Conduct Commission mails

modules/puppetmaster/templates/puppet.conf
=> Revert "add /etc/puppet/ssl to basemodulepath"

modules/postfix/files/aliases
Resigning, posted @ [Meta](https://meta.miraheze.org/w/index.php?title=Stewards%27_noticeboard&diff=41297&oldid=41296).
=> [Postfix] Remove revi from cvt@ alias

modules/puppetdb/manifests/database.pp
We will have to do this manually as there seems to be no easy way of doing it.
=> Cross out create_tgrm_extension

modules/postgresql/manifests/master.pp
=> Cross out pg-initdb

modules/puppetdb/manifests/init.pp
Temp fix and just for today, until we can discuss getting more resources for puppet1.
=> Lower heap_size to 300mb

modules/phabricator/data/config.yaml
Logo is 80x80px version of Miraheze logo, wordmark/text reads Miraheze. File is here. https://phabricator.miraheze.org/F745359
=> Customize Phab Logo/Wordmark

modules/postgresql/files/tuning.conf, modules/postgresql/manifests/server.pp
We can tune it so that it try to use less ram
=> Add tuning.conf to postgres

manifests/site.pp
=> Revert "Include testpuppetdb module temporarily"

hieradata/hosts/puppet1.yaml, modules/puppetdb/manifests/database.pp, modules/puppetdb/manifests/init.pp, modules/puppetmaster/manifests/puppetdb/client.pp
=> Revert "Enable ssl connection to postgresql and use db4 as host"

hieradata/hosts/puppet1.yaml, modules/puppetdb/manifests/database.pp, modules/puppetdb/manifests/init.pp, modules/puppetmaster/manifests/puppetdb/client.pp
=> Revert "Revert "Enable ssl connection to postgresql and use db4 as host""

modules/puppetdb/manifests/init.pp
We have enough cores to run threads as 2
=> Increase puppetdb::command_processing_threads to 2

modules/mediawiki/manifests/init.pp
This is to make sure that cloning works before creating any files here
=> Make sure that 'MediaWiki config' has finished cloning

modules/httpd/files/apache-status, modules/httpd/files/defaults.conf, modules/httpd/files/dummy.conf, modules/httpd/files/status.conf, modules/httpd/manifests/conf.pp, modules/httpd/manifests/init.pp, modules/httpd/manifests/mod_conf.pp, modules/httpd/manifests/mpm.pp, modules/httpd/manifests/site.pp, modules/stdlib/lib/puppet/parser/functions/require_package.rb
This module is copied from wmf's one that is intended to replace the apache one
see https://github.com/wikimedia/puppet/blob/production/modules/httpd/
=> Add new httpd module

modules/ganglia/manifests/init.pp, modules/httpd/manifests/mod.pp, modules/icinga/manifests/init.pp, modules/phabricator/manifests/init.pp, modules/piwik/manifests/init.pp, modules/puppetmaster/manifests/init.pp
=> Add mod.pp

modules/parsoid/manifests/init.pp
=> Revert "Downgrade parsoid to 0.8.0 temporarily due to breaking changes with 0.9.0"

modules/varnish/files/icinga/check_varnishbackends.py
Also adds a space between the backend names
=> Replace boot. so that it shows only the backend name

modules/base/files/ganglia/modpython.conf, modules/base/manifests/monitoring.pp
Following https://github.com/ganglia/monitor-core/wiki/Ganglia-GMond-Python-Modules
=> Add modpython.conf to ganglia

modules/postfix/files/aliases, modules/users/data/data.yaml
See [T3404](https://phabricator.miraheze.org/T3404).
=> Remove revi's key

modules/varnish/templates/default.vcl
I know that the spacing is probably off. Draft: https://test1.miraheze.org/503.html
=> redesign varnish error pages

modules/mariadb/templates/config/mw.cnf.erb
It keeps using too much storage
=> Set slow-query-log to 0

modules/httpd/manifests/conf.pp, modules/httpd/manifests/init.pp, modules/httpd/manifests/mod.pp, modules/httpd/manifests/mod_conf.pp, modules/httpd/manifests/mpm.pp, modules/httpd/manifests/site.pp, modules/stdlib/sourceurl.pp
Copys from upstream https://github.com/wikimedia/puppet/blob/production/modules/httpd
=> Convert httpd class to use puppet types per T3635

modules/acme/files/mirahezerenewssl.py, modules/acme/files/ssl-acme
=> Remove -a param from ssl-renew

modules/mediawiki/files/dumps/dumpsBackup.sh, modules/mediawiki/manifests/dumps.pp
Will be used to run wiki dumps.
=> Add new dumpsBackup.sh script

modules/parsoid/manifests/init.pp, modules/parsoid/templates/parsoid.systemd.erb
Instead of using the package lets use the git repo.
=> Update parsoid to use the git repo

modules/postfix/files/aliases
So that all mails go to mailing list.
=> Update conduct@ and cocc@

modules/phabricator/files/phab.miraheze.wiki.conf, modules/phabricator/manifests/init.pp
=> Update phab.miraheze.wiki to use miraheze.wiki cert

modules/mediawiki/manifests/jobrunner.pp
=> Add a "generate sitemaps for all wikis" cron fixes T1765

modules/mediawiki/manifests/packages.pp
Per https://phabricator.miraheze.org/T3894
=> Install Inkscape on mw*

modules/irc/manifests/irclogbot.pp, modules/irc/manifests/ircrcbot.pp, modules/irc/templates/initscripts/ircrcbot.systemd.erb, modules/irc/templates/initscripts/logbot.systemd.erb
Also rename adminbot to logbot. Was incorrectly named as it's not a admin bot.
=> irc: Switch service to use systemd module

modules/monitoring/templates/ssl.conf.erb
Otherwise you have a duplicate check for the miraheze.wiki wildcard cert
=> Rm phab.miraheze.wiki check

modules/postfix/files/aliases
per https://meta.miraheze.org/w/index.php?oldid=73946#.E9.96.8B.E6.8B.93.E8.80.85.27s_Request_for_Stewardship
=> move The Pioneer to stewards

modules/mediawiki/manifests/nginx.pp, modules/puppetserver/manifests/init.pp, modules/services/manifests/citoid.pp, modules/services/manifests/restbase.pp, modules/ssl/manifests/hiera.pp, modules/varnish/manifests/nginx.pp
=> Revert "Change /etc/puppet to /etc/puppetserver/puppet"

modules/postfix/files/aliases
use the old address that was present before
=> send cvt mail to macfan

modules/base/manifests/init.pp, modules/base/manifests/sysctl.pp
This tweeks the network params and also changes a few other sysctl settings
=> base: Introduce base::sysctl

modules/lizardfs/templates/mfschunkserver.cfg.erb
@paladox @JohnFLewis please approve ASAP (not sure if this will impact anything but won't push without approval)
=> HDD_LEAVE_SPACE_DEFAULT to 12 GB (lack of disk space)

modules/ssl/manifests/wildcard.pp
=> Revert "Set wildcard cert permissions to 0600"

modules/grafana/files/nginx/grafana.conf, modules/icingaweb2/files/icinga2.conf, modules/lizardfs/files/nginx/nginx.conf, modules/matomo/files/nginx.conf, modules/mediawiki/templates/mediawiki.conf, modules/nginx/templates/nginx.conf.erb, modules/phabricator/files/phab.miraheze.wiki.conf, modules/phabricator/files/phabricator.miraheze.org.conf, modules/prometheus/templates/initscripts/nginx-prometheus-exporter.systemd.erb, modules/roundcubemail/files/mail.miraheze.org.conf, modules/roundcubemail/files/roundcubemail.conf, modules/services/files/nginx/mathoid, modules/services/files/nginx/parsoid, modules/services/files/nginx/restbase, modules/varnish/templates/mediawiki.conf
=> Move /server-status to the nginx config

modules/lizardfs/manifests/storage.pp, modules/lizardfs/templates/mfshdd.cfg.erb
This variable will allow us to remove chunkservers.
=> lizardfs: Add chunkserver_mount_removal variable

modules/varnish/templates/default.vcl
Do not merge unless you are sure of this change.
=> temp fix electronpdfservice from displaying CookieWarning

modules/prometheus/manifests/init.pp, modules/prometheus/templates/prometheus.yml.erb
=> Revert "prometheus: Use ip instead of fqdn"

modules/mediawiki/templates/mediawiki.conf
Will be used to trial glusterfs for a few wikis.
=> mediawiki: Add static-temp

manifests/site.pp, modules/modules/role/files/staticserver/exports, modules/nfs/manifests/client.pp, modules/nfs/manifests/server.pp, modules/role/manifests/mediawiki.pp, modules/role/manifests/staticserver.pp
We will connect nfs to the lizard master which will have a mount which connects to the lizard master.
=> Reintroduce nfs

hieradata/hosts/misc3.yaml, modules/base/manifests/sysctl.pp
Also set base::sysctl::swap_value to 0 for misc3
=> base: Allow changing swappiness value through hiera

modules/mediawiki/manifests/php.pp, modules/php/manifests/fpm/pool.pp
Also increase max_requests to 3000
=> mediawiki: Tweak php config

modules/lizardfs/manifests/master.pp, modules/lizardfs/templates/globaliolimits.cfg.erb
=> lizardfs: Add globaliolimits and configure it

modules/monitoring/files/users.conf
I see them when I’m here on irc and all they do is clog my inbox
=> Disable mail notify for rhinosf1

hieradata/hosts/lizardfs6.yaml, manifests/site.pp, modules/mediawiki/manifests/init.pp, modules/mediawiki/manifests/php.pp
Also tweek php-fpm childs to around 50.
=> Add lizardfs6 as a mediawiki server

modules/varnish/templates/default.vcl
=> varnish: Fix regex

modules/varnish/templates/default.vcl
=> Varnish: Fix regex part 2

modules/postfix/files/aliases
T5016
Ensure full consensus and check any config for maniphest
=> Update with new role titles

modules/postfix/files/aliases
=> Remove labster from tech@

hieradata/common.yaml, hieradata/hosts/lizardfs6.yaml, modules/mediawiki/manifests/init.pp
Also switch on redis and also set heap to 3000mb for lizardfs6
=> mediawiki: Add a local redis instance configurable by use_redis

hieradata/hosts/jobrunner1.yaml, manifests/site.pp
Also install redis locally with 1gb of heap
=> Make jobrunner1 a mediawiki jobrunner

hieradata/hosts/mon1.yaml, manifests/site.pp
=> mon1: Install Grafana, Icinga2 and Prometheus

hieradata/hosts/mw1.yaml, hieradata/hosts/mw2.yaml, hieradata/hosts/mw3.yaml
=> Revert "mw[123] increase fpm_workers_multiplier to 2.0"

modules/mariadb/templates/config/mw.cnf.erb
This will allow port 3306 to be served over both ipv6 and ipv4.
=> mariadb: Bind to ::

modules/irc/templates/ircrcbot.py
Also fix 'builtins.AttributeError: 'NoneType' object has no attribute 'gotUDP''
Bug: T5462
=> ircrc: Fix small bug related to messages comming in all at the same time

modules/profile/files/openldap/modify-ldap-group, modules/profile/files/openldap/modify-ldap-user, modules/profile/manifests/openldap.pp
From upstream https://github.com/wikimedia/puppet/blob/618865b16e1fe782a970f8994b947e9aa1272e0a/modules/ldap/files/modify-ldap-user & https://github.com/wikimedia/puppet/blob/618865b16e1fe782a970f8994b947e9aa1272e0a/modules/ldap/files/modify-ldap-group
=> openldap: Add some scripts to make it easy to edit user/group in ldap

modules/monitoring/files/users.conf
=> Zppix is a puppetuser now

modules/varnish/templates/default.vcl
=> varnish: Redirect /wiki/undefined and /w/undefined to /w/api.php

modules/varnish/manifests/init.pp, modules/varnish/templates/default.vcl
=> Add jobrunner1 to purge list

modules/role/manifests/grafana.pp
=> grafana: remove firewall

modules/monitoring/files/users.conf, modules/postfix/files/aliases, modules/users/data/data.yaml
https://phabricator.miraheze.org/T5782
=> Access: Restore rhinosf1 [mw-admin]

modules/postfix/files/aliases
To discuss with Ferran so we can have an email for the accounts the bot uses
=> add bots email per T5845

modules/irc/manifests/ircrcbot.pp, modules/irc/templates/ircrcbot.py, modules/role/manifests/irc.pp
=> ircrcbot: Fix "unexpected end of data"

modules/mediawiki/manifests/jobrunner.pp
=> jobrunner: Don't nice scripts

modules/mediawiki/files/robots.php
It's hitting at an insane rate of just over one query per second on a single mw
=> add a throttle for BingBot

modules/mediawiki/manifests/jobrunner.pp
~~needs a change to https://github.com/miraheze/MirahezeMagic/blob/master/maintenance/populateWikibaseSitesTable.php#L55 make it not wikibase specific first~~
=> +2 crons for GlobalUsage

modules/varnish/templates/mediawiki.conf
=> Revert "403 clients with no UserAgent"

modules/monitoring/files/check_reverse_dns.py
should make https://icinga.miraheze.org/monitoring/event/show?type=notify&id=134112 more clear, a bit of a proof of concept without tests but it works in my sleepy head.
=> check_reverse_dns: handle an exception

modules/varnish/templates/mediawiki.conf
=> Revert "Revert blocking empty user agents"

modules/varnish/templates/mediawiki.conf
Rough idea as I'm mobile, please check syntax & format
=> mediawiki-varnish: block some IPs

modules/varnish/manifests/nginx.pp, modules/varnish/templates/mediawiki.conf
=> Revert "varnish: Fix rate limiter"

modules/monitoring/files/check_reverse_dns.py
=> Catch resolver.NoAnswer

modules/mediawiki/templates/mediawiki.conf.erb
I think this would work? I'm not entirely sure.
=> miraheze.org: redirect /discord to our discord invite

modules/mediawiki/templates/PrivateSettings.php
=> Revert "array()->[] (in PrivateSettings.php template)"

hieradata/hosts/puppet2.yaml, modules/puppetdb/manifests/init.pp
* Up the heap for puppetserver and puppetdb
* Decrease puppetdb command processing to 1
=> puppet: Tweak configuration

hieradata/hosts/jobrunner1.yaml, hieradata/hosts/jobrunner2.yaml, hieradata/hosts/mw4.yaml, hieradata/hosts/mw5.yaml, hieradata/hosts/mw6.yaml, hieradata/hosts/mw7.yaml, hieradata/hosts/services1.yaml, hieradata/hosts/services2.yaml, hieradata/hosts/test2.yaml, modules/base/manifests/puppet.pp, modules/base/templates/puppet/puppet-run.erb, modules/base/templates/puppet/puppet.cron.erb
* Randomises puppet runs with a config that can specify a time
* Uses new puppet-run script to run puppet
=> base::puppet: Update puppet cron

modules/varnish/templates/default.vcl
See https://github.com/matomo-org/matomo/issues/16935
=> Varnish: Add connect-src 'self' to csp if host is mon1.miraheze.org

modules/varnish/templates/default.vcl
=> Revert "Depool mw5"

modules/users/data/data.yaml
=> data: upgrade my ssh key to ed25519

modules/mediawiki/files/sitemap.php, modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/mediawiki.conf.erb
This is so when fetching /sitemap.xml it'll redirect to the correct link
=> mediawiki: Rewrite /sitemap.xml to sitemap.php

modules/mediawiki/files/robots.php
=> robots: block %3A where : is

modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/PrivateSettings.php
GoogleMaps does not seem to work anymore as it is paid. Therefore this should be removed.
=> Remove $wmgMapsGMaps3ApiKey from PrivateSettings template

modules/role/manifests/cloud.pp
Very minor change to just a php comment
=> Update PHP comment to cloud 4 and 5 not 1 and 2

modules/mediawiki/manifests/jobrunner.pp
So we can handle extracting rar files for imports
=> jobrunner: install unrar

modules/mediawiki/manifests/jobrunner.pp
=> Revert "jobrunner: install unrar"

hieradata/hosts/rdb4.yaml, manifests/site.pp
=> Reinstall rdb4 as mc2

modules/vmlib/lib/puppet/functions/wmflib/expand_path.rb
This is from https://github.com/wikimedia/puppet/commit/c2014c36a449ae1841508e24ac3b094dee3bb62f.
This will allow us to at some point define hiera values per class.
=> Add expand_path

modules/role/files/elasticsearch/index_template.json, modules/role/manifests/graylog.pp
=> graylog: Set max_result_window to 10000000 on graylog template

modules/gluster/manifests/init.pp, modules/gluster/manifests/logging.pp
This is to allow us to read files such as glusterd.log and send to gluster.
Bug: T5044
=> Introduce gluster::logging

modules/varnish/templates/default.vcl
Redoing #1680 due to mess up with a merge conflict resolution
=> Varnish: Add X-Robots-Tag http header (Should fix T6680)

modules/gluster/files/glusterfs-common.logrotate.conf, modules/gluster/manifests/init.pp
Reloads syslog-ng when rotating glusterfs.log.
=> gluster: Add logrotate

modules/mediawiki/files/mediawiki-firejail-ghostscript.py, modules/mediawiki/manifests/packages.pp
Seems to be required for pdfhandler
=> Install ghostscript on all mediawiki servers

manifests/site.pp, modules/prometheus/templates/prometheus.yml.erb
This will provide us some metrics.
=> Monitor test4 in blackbox_https_mediawiki_cp

modules/gluster/manifests/mount.pp
=> gluster: Don't use exec to create mount directory

modules/mediawiki/templates/mediawiki-includes.conf.erb
=> Redirect Redirect /entity/* to /wiki/Special:EntityData/*

modules/mediawiki/manifests/extensionsetup.pp
=> Remove composer for Validator

modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/PrivateSettings.php
See miraheze/mw-config#3854 for context.
=> Remove  wmgYandexTranslationKey

modules/mediawiki/manifests/init.pp
=> Revert "set depth to 1 instead of 5 for cloning core"

hieradata/common.yaml, hieradata/hosts/test3.yaml
=> Switch test3 to 1.36 stuff

hieradata/common.yaml
=> Super Gnomey edit to remove extra space

modules/role/files/mediawiki/bin/remountGluster.sh, modules/role/manifests/mediawiki.pp
Run the cron every minute.
Bug: T7287
=> mediawiki: Check that gluster is mounted

hieradata/hosts/mw10.yaml, hieradata/hosts/mw11.yaml, hieradata/hosts/mw8.yaml, hieradata/hosts/mw9.yaml
Doubled from 26 to 32 (we can handle it memory rise)
=> mediawiki: Increase php childs to 32

modules/cloud/manifests/init.pp, modules/cloud/templates/mdadm-cron.erb
Copied from https://github.com/wikimedia/puppet/commit/650f9a5e95b0872a0d1c4babf2424546ecf1e9e8
=> cloud: randomise mdadm cron

modules/monitoring/files/check_reverse_dns.py
=> Revert "monitoring: Fix support for python3 in check_reverse_dns"

modules/mediawiki/files/robots.php
Since its done with https://github.com/miraheze/puppet/blob/79340d4/modules/varnish/templates/default.vcl#L405
=> Remove DISALLOW stuff from robots.txt user-agent: *

modules/monitoring/files/users.conf, modules/users/data/data.yaml
Thank you for your service! :(
=> remove paladox sre access per resignation

modules/irc/templates/logbot/config.py
* Add Voidwalker
* Remove SPF|Cloud as it seems is using Southparkfan on IRC now. I'll undo this part of this PR if that is necessary.
* Remove myself as I no longer use Crepusculum
=> Update IRC logbot author_map

modules/monitoring/files/check_reverse_dns.py, modules/monitoring/manifests/init.pp
Part of the SSL Automation project
=> check_rdns: validate records in use

modules/monitoring/files/check_reverse_dns.py
/me groans something about debian being too stable
=> rdns: apparently Resolve ain't added. yet

modules/monitoring/files/check_reverse_dns.py
.sort() is giving None wrongly
=> rdns: use sorted over .sort()

modules/monitoring/files/check_reverse_dns.py
This is used forced on for free users. It won't cause any harm so assume it's fine.
=> rdns: ignore missing CNAME for CF at root

modules/monitoring/files/check_reverse_dns.py
=> Revert "rdns: ignore missing CNAME for CF at root"

modules/monitoring/files/check_reverse_dns.py
=> Revert "Revert "rdns: ignore missing CNAME for CF at root""

hieradata/hosts/jobrunner3.yaml, hieradata/hosts/jobrunner4.yaml, hieradata/hosts/mw10.yaml, hieradata/hosts/mw11.yaml, hieradata/hosts/mw9.yaml, hieradata/hosts/test3.yaml
Reverts miraheze/puppet#1825
Doesn't seem to have a significant impact. Also introduces drift between servers
=> Revert "puppet: rebalance MediaWiki puppet times "

hieradata/common.yaml, hieradata/hosts/test3.yaml, modules/mediawiki/manifests/init.pp
=> Revert "test3: clone mediawiki as staging"

hieradata/common.yaml, hieradata/hosts/test3.yaml, modules/mediawiki/manifests/init.pp
=> Revert "Revert "test3: clone mediawiki as staging""

modules/base/templates/icinga/nrpe.cfg.erb, modules/varnish/files/stunnel/stunnel.conf, modules/varnish/manifests/stunnel4.pp
=> Revert "T7718: Remove stunnel check for test3"

modules/varnish/templates/default.vcl
Will be the home of the new ssl portal
=> varnish: force sslrequest. to jbr3

modules/mediawiki/manifests/init.pp
=> Revert "mediawiki: don't auto sync config"

hieradata/hosts/puppet3.yaml, modules/base/manifests/puppet.pp, modules/role/manifests/puppetserver.pp
=> Upgrade to puppet 7 everywhere

modules/users/data/data.yaml
7.2 isn't used; 7.4 will be soon
=> users: allow MediaWiki-admin php7.4; drop 7.2

modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/mediawiki.conf.erb
=> mediawiki: Add custom 404 to nginx

modules/mediawiki/manifests/extensionsetup.pp, modules/mediawiki/manifests/packages.pp
DO NOT MERGE until bullseye upgrades are done. Buster native packages are v1.
=> Update to composer v2

modules/varnish/data/csp.yaml
Approved in T5869 following the CSP policy
=> add imgbb.com & postimages.org to CSP whitelist T5869

modules/mediawiki/files/bin/mwscript.py
The script is no longer used and will soon be deleted.
=> mwscript: remove exception for RemovePII maintenance script

hieradata/hosts/mw8.yaml
=> Revert "mw8: update php"

modules/mediawiki/manifests/extensionsetup.pp
* Per https://github.com/femiwiki/FemiwikiSkin/issues/311#issuecomment-922267044
=> MediaWiki: install Femiwiki npm dependencies

modules/varnish/templates/default.vcl
Otherwise we can't check it is online.
=> varnish_x-debug: add mwtask1_test

modules/mediawiki/files/bin/deploy-mediawiki
=> mwdeploy: fix rsync --delete usage; add some logging

modules/mediawiki/files/bin/deploy-mediawiki
Doesn't work and afaics not needed
=> mwdeploy: don't sync cache/l10nupdate-*.json

modules/mediawiki/files/bin/deploy-mediawiki.py
=> mwdeploy: pin gitinfo to world

modules/mediawiki/files/bin/deploy-mediawiki.py, modules/mediawiki/manifests/init.pp
Reverts miraheze/puppet#2113
This did us no good whatsoever.
=> Revert "mwdeploy: improve l10nupdate performance"

modules/php/manifests/fpm/pool.pp
Mitigate memory leaks of php 7.4 on bullseye
=> php-fpm: reduce pm.max_requests

modules/mediawiki/manifests/extensionsetup.pp
=> Revert "composer: disable maps"

hieradata/hosts/mw8.yaml
Reverts miraheze/puppet#2164
Done for now.
=> Revert "mw8: temporary revert of php-fpm changes (in order to debug)"

modules/mediawiki/files/bin/deploy-mediawiki.py
=> Revert "mwdeploy: depool mw8 for testing"

modules/php/manifests/fpm/pool.pp
I'm not sure this is needed yet but I'm creating just in case. I'll review the graphs over tomorrow.
I kinda hope not because our other changes should have had a big impact but we still need to see what the graph looks like over a longer period and what happens. I'm going to try and decide by tomorrow evening because it's getting close to Christmas.
=> php: lower pm.max_requests to 1,000

modules/ssl/manifests/hiera/certs.pp
ats is no longer being tested and was removed
=> Remove regex_domain_ats

manifests/site.pp, modules/role/manifests/bastion.pp
Open port 8080 to traffic from our vms
=> Add bastion role file

modules/varnish/templates/default.vcl
- seperate PR will exist to switch rotation when ready
=> varnish: add new mw servers

modules/varnish/data/csp.yaml
=> CSP: add `'blob:'` to `img-src`

manifests/site.pp
To make them easier to remove when the time comes.
=> site: split SCSVG and Ovlon MediaWiki servers

hieradata/hosts/jobchron1.yaml, hieradata/hosts/jobchron121.yaml, modules/mediawiki/manifests/php.pp, modules/php/manifests/init.pp, modules/php/manifests/php_fpm.pp, modules/vmlib/types/php_version.pp
Sometimes we only want the cli not fpm.
=> php: Allow disabling fpm

hieradata/common.yaml, modules/mediawiki/files/shellbox_config.json, modules/mediawiki/manifests/init.pp, modules/mediawiki/manifests/shellbox.pp, modules/mediawiki/templates/PrivateSettings.php, modules/mediawiki/templates/shellbox.internal.erb, modules/php/manifests/php_fpm.pp
For T5863
Following https://www.mediawiki.org/wiki/Shellbox
However, I don't know what do for the apache setup, since we use nginx.
=> MediaWiki: configure shellbox

modules/mediawiki/manifests/shellbox.pp
To not be dependant on staging
=> shellbox: use composer.phar

modules/users/data/data.yaml
=> Revert "Add new key for paladox"

modules/mediawiki/manifests/jobqueue/runner.pp
=> Revert "jobs::cron: disable misbehaving scripts"

hieradata/hosts/mon111.yaml
=> mon111: reduce php childs

modules/monitoring/templates/ssl.conf.erb
=> monitoring: Increase check_interval for reverse dns and ssl check

modules/grub/manifests/bootparam.pp, modules/grub/manifests/defaults.pp, modules/grub/manifests/init.pp, modules/mediawiki/files/cgroup/cgroup-mediawiki-clean, modules/mediawiki/manifests/cgroup.pp, modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/initscripts/mw-cgroup.systemd.erb
NOTE: this will require servers to be rebooted.
=> MediaWiki: support control groups

modules/mediawiki/manifests/jobqueue/runner.pp
=> absent manageInactiveWikis cron

modules/mediawiki/manifests/jobqueue/runner.pp
=> Revert "absent manageInactiveWikis cron"

modules/mediawiki/manifests/extensionsetup.pp, modules/mediawiki/manifests/packages.pp, modules/mediawiki/manifests/shellbox.pp
This should work for composer v2 since we are on Bullseye now.
=> MediaWiki: Use Debian composer package

modules/mediawiki/manifests/jobqueue/runner.pp
=> Revert "Revert "absent manageInactiveWikis cron""

modules/mediawiki/manifests/jobqueue/runner.pp
=> Revert "Revert "Revert "absent manageInactiveWikis cron"""

modules/base/manifests/firewall.pp
Of course I managed to break this when fixing merge conflicts. Sorry!
=> base::firewall: fix ssh rule

modules/mediawiki/manifests/packages.pp
=> MediaWiki: Remove ffmpeg2theora

modules/mediawiki/files/bin/deploy-mediawiki.py
=> Revert "deploy-mediawiki: temporarily disable canary check"

modules/mediawiki/manifests/extensionsetup.pp
=> Revert "Add Elastica composer"

modules/mediawiki/templates/jobrunner-hi.json.erb, modules/mediawiki/templates/jobrunner.json.erb
=> Revert "jobrunner: add low-priority jobs"

modules/varnish/templates/default.vcl
First change was suggested by @AgentIsai; second change corrects the wording from "sysadmins" to "Site Reliability Engineering"
=> Tweaking wording of 503 backend fetch error page

modules/varnish/templates/default.vcl
Reverts miraheze/puppet#2415
needs more discussion, it reads horribly. I've never heard anyone in my life say as soon as humanely possible to humans and I spend all day with people who have come out with pretty much anything a person could possibly come up with.
=> Revert "Tweaking wording of 503 backend fetch error page"

hieradata/common.yaml, hieradata/hosts/mwtask111.yaml
=> Use default_sync = all everywhere

modules/mediawiki/templates/jobrunner-hi.json.erb, modules/mediawiki/templates/jobrunner.json.erb, modules/prometheus/files/redis/jobQueueCollector.lua
It is, test101's cpu will tell you.
=> RecordLintJob: move to intensive

modules/redis/templates/initscripts/redis-server.systemd.erb
We want to be able to write to /srv/redis
=> redis: Fix redis systemd config

modules/mediawiki/manifests/extensionsetup.pp
https://github.com/miraheze/femiwiki-deploy
=> Remove femiwiki_npm

modules/mediawiki/manifests/init.pp
I'm not sure this'll work or is the best approach, but simple git clone likely won't work here due to doing inside submodule, and the fact that we need to pull only node_modules from the deploy repo.
=> Use femiwiki-deploy

modules/mediawiki/manifests/init.pp
=> Revert "Use femiwiki-deploy"

modules/users/data/data.yaml
=> Revert "Remove SSH key for Universal Omega"

modules/mariadb/manifests/config.pp, modules/mariadb/manifests/instance.pp
=> Add MariaDB doc entries

modules/mediawiki/templates/jobrunner-hi.json.erb
This reverts commit b4b97298fe911d9ca826308d3f1fffab93364399.
=> Revert "jobrunner: Re add nice"

modules/irc/files/logbot/adminlog.py, modules/irc/manifests/irclogbot.pp, modules/irc/templates/logbot/config.py
https://mwclient.readthedocs.io/en/latest/user/connecting.html#oauth
=> logbot: Use OAUTH for login

modules/mediawiki/templates/mediawiki-includes.conf.erb, modules/mediawiki/templates/mediawiki.conf.erb
To work with custom domains as well
=> move static alias to mediawiki-includes

hieradata/hosts/test101.yaml
=> test: update to 1.38

hieradata/hosts/matomo101.yaml
3 x 2 = 6 increasing from the 4 childs available.
=> matomo101: increase php::php_fpm::fpm_workers_multiplier to 3.0

hieradata/hosts/cloud10.yaml, hieradata/hosts/cloud11.yaml, hieradata/hosts/cloud12.yaml
=> Remove `install_cloud_class`

hieradata/common.yaml
=> Remove `use_gluster_new` from hieradata

modules/varnish/manifests/init.pp, modules/varnish/templates/default.vcl
=> varnish: rename `$csp_whitelist` to `$csp`

modules/users/data/data.yaml
Generated biometric key with Termius for access from my phone too
=> rhinosf1: add new key

.github/pythonchecks.txt, .github/workflows/workflow.yml, modules/letsencrypt/files/mirahezerenewssl.py, modules/letsencrypt/files/ssl-certificate.py
Supercedes #2424 due to conflicts and being able to also add new changes to ssl-certificate to make those pass in CI also.
=> LetsEncrypt: fix flake8 violations and add to CI

modules/mediawiki/templates/jobrunner.json.erb
Reverts miraheze/puppet#2581
Doesn't work well in our current setup
=> Revert "jobrunner: set maxjobs to 1"

modules/roundcubemail/templates/config.inc.php.erb
Per [T9309](https://phabricator.miraheze.org/T9309).
=> Increase roundcube session lifetime to 60 minutes

modules/monitoring/files/grafana-webhook.py
=> Revert "Attempt to fix grafana-webhook"

modules/monitoring/files/grafana-webhook.py
* Check if page label exists
* Always uppercase status within message
* Remove hard-coded MediaWiki dashboard URL
=> Minor fixes to grafana-webhook

modules/monitoring/files/grafana-webhook.py
=> grafana-webhook: move all dashboard stuff to same if statement

hieradata/hosts/matomo101.yaml
Lowers memory usage and also possibly cpu.
=> matomo101: lower php childs

modules/roundcubemail/templates/config.inc.php.erb
Per [T9309](https://phabricator.miraheze.org/T9309).
=> Increase roundcube session lifetime to 24 hours

modules/monitoring/files/check_reverse_dns.py
Fixes the syntax error present in the previous PR that was reverted.
=> Cleanup check_reverse_dns

modules/mediawiki/files/bin/deploy-mediawiki.py, modules/mediawiki/files/bin/test_mw_deploy.py
=> mwdeploy: backport a fix

modules/mariadb/manifests/config.pp
=> mariadb: send mysql-error.log to graylog

modules/role/manifests/graylog.pp
=> graylog: rsyslog parse /var/log/graylog-server/graylog-server.log

modules/prometheus/files/redis/jobQueueCollector.lua
Per https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Translate/+/774463
=> jobQueueCollector: add TranslatableBundleDeleteJob

hieradata/hosts/matomo101.yaml
=> Revert "matomo101: increase php fpm childs to 9 x core (so 9x2 atm = 18) (#2707)"

modules/users/data/data.yaml
=> users: add varnishlog and varnishstat to cache-admins

modules/base/lib/facter/numa.rb
From https://github.com/wikimedia/puppet/blob/280212a072f22371d59855223eb256a63a13dc9e/modules/base/lib/facter/numa.rb
=> base: Add numa facter

hieradata/hosts/db111.yaml, manifests/site.pp
> 03:49 paladox: delete db111 vm
=> Remove db111

modules/icingaweb2/templates/roles.ini.erb
This is not intended to support sre in the mediawiki team. Adding myself manually in this case should work.
=> icingaweb2: add myself to "Administrators" role

modules/varnish/manifests/stunnel4.pp, modules/varnish/templates/initscripts/stunnel4.systemd.erb
Also increase open files / file descriptors to 500000
=> Make stunnel use systemd

hieradata/common.yaml, modules/role/manifests/mediawiki/nutcracker.pp
=> Revert "Convert memcached_servers to single nutcracker config in hiera"

hieradata/hosts/mw122.yaml
=> Revert "mw122: enable request profiling"

modules/base/files/dns/recursor.conf
See https://doc.powerdns.com/recursor/settings.html#allow-from
=> powerdns: fix allow-from

modules/systemd/manifests/syslog.pp
From https://github.com/wikimedia/puppet/blob/production/modules/systemd/manifests/syslog.pp
=> Add systemd::syslog module

modules/php/manifests/fpm/pool.pp
From https://github.com/wikimedia/puppet/commit/9d5e6c7cc42a3462cf475daa7fbfb7c0fb4d55c6
=> php::fpm::pool: fix race condition

modules/varnish/templates/default.vcl
This will make the use of ipv6 with fallback of ipv4.
=> varnish: connect to stunnel using localhost

modules/icingaweb2/templates/roles.ini.erb
=> Revert "icingaweb2: add myself to "Administrators" role"

modules/mediawiki/manifests/extensionsetup.pp
Requires https://github.com/miraheze/mediawiki/pull/9336
=> Support PageProperties 1.1.0

modules/varnish/templates/default.vcl
=> Revert "varnish: fix address (should be `::6`)"

modules/prometheus/templates/blackbox_exporter.yml.erb, modules/role/manifests/prometheus.pp
It was disabled, but now the positive affect it seemed to have, there is no intent to re-add it at this time.
=> Completely remove blackbox from MediaWiki

modules/swift/templates/object-server.conf.erb
Also set some of the configs under object-auditor
=> swift: cleanup object-auditor within object-server

modules/swift/templates/object-server.conf.erb
Also increase keep_cache_size to 200MB from 5MB.
=> swift: cleanup app:object-server within object-server

modules/swift/manifests/storage.pp, modules/swift/templates/object-server.conf.erb
Also introduce a config to make workers configurable.
=> swift: cleanup default within object-server

modules/swift/manifests/init.pp, modules/swift/templates/swift-env.sh.erb
=> Swift: add swift-env.sh

hieradata/hosts/swiftobject111.yaml, hieradata/hosts/swiftobject112.yaml, hieradata/hosts/swiftobject113.yaml, hieradata/hosts/swiftobject114.yaml, hieradata/hosts/swiftobject115.yaml, hieradata/hosts/swiftproxy111.yaml, hieradata/hosts/swiftproxy131.yaml, modules/swift/templates/account-server.conf.erb, modules/swift/templates/container-server.conf.erb
=> Revert "swift: increase workers"

modules/varnish/templates/default.vcl
=> T9808: assign restrictive cache-control if one is missing

modules/swift/files/SwiftMedia/miraheze/rewrite.py
We rewrite the url if done using AUTH or PUT/POST/DELETE. In MW we cannot change the path like we can for FS so we have to do this our end using the rewrites.
This should catch most use cases but if there's a missing one just add it.
=> swift: add rewrites

hieradata/hosts/swiftobject114.yaml
Uses the common configuration which is 48 workers
=> swift: fix swiftobject114 workers

modules/mediawiki/files/robots.php, modules/mediawiki/files/sitemap.php
Just use $wmgUploadHostname for now to support getting static-new if on Swift
=> Support Swift in robots.php and sitemap.php

modules/swift/manifests/proxy.pp
=> swift: fix proxy monitoring

modules/varnish/templates/default.vcl
Syncs 503 error with the other ErrorPage errors by adding support for dark mode and changes the button color along with changing wording a bit
=> Sync 503 with all other ErrorPages

hieradata/hosts/swiftobject114.yaml
=> Revert "swiftobject114/5: reduce workers"

hieradata/hosts/swiftobject114.yaml, hieradata/hosts/swiftobject115.yaml
=> swiftobject114/5: reduce workers

modules/swift/templates/proxy-server.conf.erb
Also unset conn_timeout as it defaults to node_timeout.
=> swift: increase node_timeout to 40s

modules/mediawiki/templates/jobrunner-hi.json.erb, modules/mediawiki/templates/jobrunner.json.erb
Also slightly tweak the config.
=> jobrunner: increase default memory limit to 300M

modules/mediawiki/templates/mediawiki.conf.erb
* miraheze/landing#93 updates links to use this format.
=> mediawiki-landing: rewrite `?lang=` to `/lang`

modules/swift/templates/proxy-server.conf.erb
=> swift: remove node timeout and conn timeout from proxy

modules/icingaweb2/manifests/init.pp, modules/role/manifests/icinga2.pp
doesn't appear to be used within the module?
=> icingaweb2: remove use of icinga_api_password

modules/monitoring/manifests/init.pp
=> monitoring: remove /var/lib/nagios/id_rsa2

modules/varnish/manifests/init.pp
=> varnish: stop mounting /var/lib/varnish

modules/swift/templates/object-server.conf.erb
Also increases concurrency to 3.
=> swift: Make object-server use default interval for replication

modules/swift/templates/proxy-server.conf.erb
https://bugs.launchpad.net/swift/+bug/1939888
https://phabricator.wikimedia.org/T288815
=> swift: set proxy-logging twice for proxy

modules/swift/files/nginx/swift.conf, modules/swift/manifests/proxy.pp, modules/swift/templates/account-server.conf.erb, modules/swift/templates/container-server.conf.erb, modules/swift/templates/initscripts/swift-proxy.systemd.erb, modules/swift/templates/object-server.conf.erb, modules/swift/templates/proxy-server.conf.erb
=> swift: change proxy port to 80

modules/mediawiki/manifests/init.pp
=> mediawiki: change type for tidy to atime

modules/mediawiki/files/bin/deploy-mediawiki.py
=> Revert "depool all servers for 1.39 upgrade from deploy"

modules/puppetserver/manifests/init.pp, modules/puppetserver/templates/updatesfs
SFS doesn't have a crontab or a script which automatically updates it which means whatever local copy of it exists is severely outdated
=> Automatically update StopForumSpam list

modules/mediawiki/manifests/init.pp, modules/puppetserver/templates/geoipupdate
=> Get more IP databases

modules/role/manifests/db.pp
Renames some of the log files to contain -weekly/fortnightly/monthly.
=> db: redirect output of log file with 2>&1 for backups

modules/varnish/data/csp.yaml
Per T5869, add Imgur and PostImages subdomains
=> Add Imgur/PostImages Subdomains Per T5869

hieradata/hosts/db101.yaml, hieradata/hosts/db131.yaml
mhglobal was now moved to db131.
=> Move mhglobal weekly backups from db101 to db131

modules/monitoring/files/users.conf, modules/users/data/data.yaml
=> remove universalomega

modules/mediawiki/manifests/extensionsetup.pp
Required for https://github.com/miraheze/mediawiki/pull/13956
=> Add composer for NearbyPages

modules/users/data/data.yaml
Approved request in T10619
DO NOT MERGE until NDA is confirmed
=> add alex (orangestar) to mw-admins

modules/varnish/templates/default.vcl
=> Revert "Return Varnish's default 200 response on all requests to static"

modules/matomo/files/optimizeMatomoTables.sh, modules/matomo/manifests/init.pp
=> add chron to optimize matomo tables

modules/users/data/data.yaml
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
I've updated my SSH key to a FIDO2 one. For extra assurance that it is me, this commit is signed using the SSH key I've used in almost all my commits in Github, and this commit message is also signed using my OpenPGP key, which I've used in almost all my emails to sre@miraheze.org
-----BEGIN PGP SIGNATURE-----
iHUEARYIAB0WIQQRreQ5NgDBvf/LwKWY3hWUKwjKAAUCZEAg4AAKCRCY3hWUKwjK
APhkAP9ot1Awbosqb976m7geD2FF25Kv2TsXze9W7X0qb+V1VAEAp0XsqtNRSiTs
0hGf4awYHOkEmt3VAE7TazpH3iwkuw4=
=iYK3
-----END PGP SIGNATURE-----
=> Update my SSH key

modules/mediawiki/manifests/init.pp, modules/mediawiki/manifests/jobqueue/runner.pp, modules/puppetserver/templates/updatesfs
Increases SFS database list date range from 30 days to 90 days, in line with WMF
Also sets a crontab to update the denylist every day.
=> Increase SFS database list range

modules/monitoring/files/users.conf, modules/users/data/data.yaml
Reverts miraheze/puppet#3225
temporarily rejoining to setup some servers to help relive the load off void
=> Revert "remove paladox shell and icinga access"

modules/elasticsearch/README.md, modules/role/manifests/db.pp, modules/role/manifests/mediawiki.pp, modules/role/manifests/prometheus.pp, modules/ssl/manifests/web.pp
=> Replace legacy facts part 2

modules/base/templates/backups/miraheze-backup.py.erb
=> Revert "miraheze-backup: don't use strings to set X-Delete-After"

modules/base/templates/backups/miraheze-backup.py.erb
=> miraheze-backup: use pigz for sql dump

hieradata/hosts/db112.yaml, modules/role/manifests/db.pp
We only want to back up specific tables on db112 due to space.
=> db: Add option to disable sql backups

modules/varnish/templates/initscripts/varnish.systemd.erb
See if this reduces our memory overhead (https://github.com/varnishcache/varnish-cache/issues/3511)
=> varnish: Set MALLOC_CONF to thp:nver

modules/base/templates/icinga/check_puppet_run.erb
Similar patch to https://github.com/wikimedia/operations-puppet/commit/5ecf24370fd893570df19ce3a94b7e219bd42145
=> check_puppetrun: Drop safe_yaml

modules/base/manifests/ssl.pp, modules/mediawiki/manifests/nginx.pp, modules/ssl/manifests/all_certs.pp, modules/ssl/manifests/cert.pp, modules/ssl/manifests/hiera/certs.pp, modules/ssl/manifests/wildcard.pp, modules/varnish/manifests/nginx.pp
This should make things more efficient.
=> ssl: add a all_certs module

modules/varnish/templates/default.vcl
We already have checks for if someone is logged in then these entry points won't be cached.
=> varnish: Allow caching api.php/rest.php

modules/postgresql/manifests/master.pp, modules/postgresql/manifests/postgis.pp, modules/postgresql/manifests/slave.pp, modules/postgresql/manifests/user.pp
This isn't guaranteed to work but the packages should install now.
=> Postgresql: Add partial support for bookworm

modules/varnish/templates/default.vcl
=> varnish: remove converting thumbs to contain -thumbnail

modules/varnish/templates/default.vcl
=> varnish: Add browsing-topics=() to Permissions-Policy

modules/base/manifests/firewall.pp
try loading the block list from a separate file that is easier to update in bulk
=> load block_abuse from a private file

modules/mediawiki/files/bin/fileLockScript.sh
=> Fix fileLockScript

modules/varnish/templates/default.vcl
Fixes an issue for desktop browsers accessing mobile view.
=> varnish: fix mobile on desktop browsers

modules/role/manifests/openldap.pp
It's now done internally and thus conflicts.
=> openldap: Remove ppolicy

modules/role/manifests/openldap.pp
=> openldap: Temporarily cross nis off

modules/monitoring/files/commands.conf, modules/nginx/manifests/site.pp
Also switch nginx to it.
There's a bug in check_http https://github.com/monitoring-plugins/monitoring-plugins/issues/1872.
=> monitoring: Add check_curl

modules/mediawiki/files/bin/deploy-mediawiki.py
This fixes support for MediaWiki 1.41.
=> deploy-mediawiki: use MirahezeMagic mergeMessageFileList script

hieradata/hosts/mem131.yaml
=> Revert "mem131: increase size to 14g"

modules/varnish/templates/default.vcl
=> Fix thumbs containing dashes

modules/mediawiki/templates/jobrunner-hi.json.erb
=> Revert "Jobrunner-hi: increase parseroidcache runners to 8"

hieradata/hosts/mw132.yaml, hieradata/hosts/mw134.yaml, modules/mediawiki/templates/jobrunner-hi.json.erb
=> disable jobrunner on mw* apart from mwtask141

modules/mediawiki/files/robots.php
* Move rules to a robots.txt file that we then read.
* Cache robots.txt by setting a cache header.
* Don't cache beta cluster.
=> Make robots.php more readable and also cache

modules/mediawiki/files/robots.php
We need access to wgServer so have to set it in the php file.
=> robots.php: Fix setting sitemap.xml

modules/mcrouter/manifests/init.pp, modules/mcrouter/templates/default.erb, modules/role/manifests/mediawiki/mcrouter.pp
And set this to true for mediawikis mcrouter.
=> mcrouter: Add new parameter disable_tko_tracking

modules/mediawiki/templates/jobrunner-hi.json.erb
Also move smw.update to the smw queue
=> jobrunner-hi: increase smw.changePropagationClassUpdate memory limits

hieradata/hosts/db151.yaml, hieradata/hosts/db161.yaml, hieradata/hosts/db171.yaml, hieradata/hosts/db181.yaml, hieradata/hosts/db182.yaml, manifests/site.pp, modules/mariadb/manifests/config.pp, modules/mariadb/manifests/packages.pp
* Also allow db151, db161, db171 to be setup.
* Add support for mariadb 10.11 to mariadb class.
=> Install db181/db182

hieradata/hosts/mw151.yaml, hieradata/hosts/mw152.yaml, hieradata/hosts/mw161.yaml, hieradata/hosts/mw162.yaml, hieradata/hosts/mw171.yaml, hieradata/hosts/mw172.yaml, hieradata/hosts/mw181.yaml, hieradata/hosts/mw182.yaml, manifests/site.pp, modules/mariadb/manifests/packages.pp
* Also allows mw151, 152, 161, 162, 171 and 172
=> Install mw181/182

hieradata/hosts/swiftac171.yaml, hieradata/hosts/swiftobject151.yaml, hieradata/hosts/swiftobject161.yaml, hieradata/hosts/swiftobject171.yaml, hieradata/hosts/swiftobject181.yaml, hieradata/hosts/swiftproxy151.yaml, hieradata/hosts/swiftproxy181.yaml, manifests/site.pp
* Also allow installation of swiftobject151/161/171, swiftproxy151 and swiftac171
=> Install swiftobject181/swiftproxy181

modules/monitoring/files/services.conf
Increase warning to 200 and critical to 300 and only apply it to the old servers (stevenage)
=> monitoring: fix ping6

hieradata/hosts/os131.yaml, hieradata/hosts/os141.yaml, hieradata/hosts/os151.yaml, modules/mariadb/manifests/packages.pp, modules/monitoring/manifests/init.pp, modules/role/manifests/opensearch.pp, modules/role/templates/opensearch/nginx.conf
* Allows configuring which node nginx should use.
* Disable tls for os151.
=> opensearch: support disabling/enabling tls

hieradata/hosts/mem151.yaml, hieradata/hosts/mem161.yaml, manifests/site.pp
=> Install mem151

modules/monitoring/files/services.conf
Also add ping (v4) for those with a private network
=> monitoring::services add exemption for cp26 ping

hieradata/common.yaml, modules/swift/files/nginx/swift.conf, modules/varnish/templates/default.vcl
No longer send swift requests to mediawiki
=> varnish: load balance swift and send request directly to swiftproxy

modules/base/manifests/firewall.pp, modules/prometheus/manifests/exporter/node.pp, modules/prometheus/manifests/exporter/varnish.pp, modules/role/manifests/bastion.pp, modules/role/manifests/graylog.pp, modules/role/manifests/matomo.pp, modules/role/manifests/mediawiki.pp, modules/role/manifests/phabricator.pp, modules/role/manifests/prometheus.pp, modules/role/manifests/swift.pp, modules/role/manifests/varnish.pp
=> ferm: add workaround for networking fact

hieradata/common.yaml, modules/role/manifests/swift.pp, modules/swift/manifests/expirer.pp, modules/swift/templates/object-expirer.conf.erb
Imported from upstream: https://github.com/wikimedia/operations-puppet/tree/production/modules/swift
=> Add swift::expirer

modules/irc/templates/initscripts/cvtbot.systemd.erb
This reverts commit 1b9ca1896d2b665cade1c8259c1d09340b8a4f2b.
=> Revert "cvtbot: fix WorkingDirectory and Environment (#3739)"

modules/monitoring/files/check_reverse_dns.py
=> check_reverse_dns CNAME should not be none

hieradata/hosts/swiftac171.yaml, hieradata/hosts/swiftobject151.yaml, hieradata/hosts/swiftobject161.yaml, hieradata/hosts/swiftobject171.yaml, hieradata/hosts/swiftobject181.yaml, hieradata/hosts/swiftproxy161.yaml, hieradata/hosts/swiftproxy171.yaml, modules/mediawiki/manifests/init.pp, modules/prometheus/manifests/exporter/statsd_exporter.pp, modules/role/manifests/prometheus/statsd_exporter.pp, modules/role/manifests/swift.pp
TODO in follow-up (maybe):
* Launch graphite (maybe) either a new server or on mon181
* Add statsd_proxy module (to graphite)
* Add statsite module
=> statsd: expand support to MediaWiki

modules/mediawiki/manifests/extensionsetup.pp
=> Revert "mediawiki::extensionsetup: add file defined check"

modules/base/files/secupgrade.sh, modules/base/manifests/init.pp
Adapted from a version given to me by UO, mostly intended for mediawiki-roots since ops can use salt instead
=> Add secupgrade.sh script

modules/mediawiki/files/bin/iaupload.py, modules/mediawiki/files/bin/mwdeploy.py, modules/mediawiki/files/bin/mwscript.py
After @RhinosF1 mentioned this to me, figured it would be good to add a comment saying these scripts will have a new home eventually.
=> Mention python-functions repository on relevant scripts

modules/varnish/templates/mediawiki.conf.erb
=> never redirect .well-known/acme-challenges

modules/role/manifests/irc.pp
So that pywikibot is managed by puppet once again
=> Reinclude the irc::pywikibot class

modules/mediawiki/data/csp.yaml
https://issue-tracker.miraheze.org/T12186
Add to connect-src for use in client-side JavaScript. Already approved.
=> T12186: Add translate.googleapis.com to CSP

hieradata/common.yaml
https://issue-tracker.miraheze.org/T12041
=> Make 1.42 the default version

modules/swift/files/SwiftMedia/wikitide/rewrite.py
https://issue-tracker.miraheze.org/T11704
=> T11704: Swift: Support Phonos

modules/matomo/manifests/init.pp
https://github.com/matomo-org/matomo/releases/tag/5.1.1
=> Matomo: upgrade to 5.1.1

modules/varnish/templates/default.vcl
=> varnish/beta: remove

modules/monitoring/files/users.conf, modules/users/data/data.yaml
=> Re-add agent shell and icinga

modules/mediawiki/manifests/php.pp
This reverts commit fe0398388a588fbfc1d61a418bd447467406d744.
=> Revert "temporarily disable error reporting for E_DEPRECATED"

modules/varnish/templates/default.vcl
=> Revert "varnish/beta: remove"

manifests/site.pp, modules/role/manifests/changeprop.pp, modules/role/manifests/db.pp, modules/role/manifests/eventgate.pp, modules/role/manifests/graylog.pp, modules/role/manifests/irc.pp, modules/role/manifests/mathoid.pp, modules/role/manifests/mediawiki.pp, modules/role/manifests/mediawiki_beta.pp, modules/role/manifests/memcached.pp, modules/role/manifests/openldap.pp, modules/role/manifests/opensearch.pp, modules/role/manifests/poolcounter.pp, modules/role/manifests/redis.pp, modules/role/manifests/swift.pp, modules/role/manifests/varnish.pp
Restrict firewall access for beta.
=> Create role for mediawiki beta

modules/changeprop/manifests/init.pp
=> Revert "Add apt source for libssl1.1"

modules/changeprop/templates/jobqueue.config.yaml.erb
We don't define realm so this would always be false.
=> changeprop: Remove use of realm in template

modules/zookeeper/templates/zookeeper.service.erb
It was looking in /usr/share/zookeeper for the jar file. But it's installed in /usr/share/java.
=> Fix starting zookeeper

modules/role/manifests/kafka.pp
This is from https://github.com/wikimedia/operations-puppet/blob/production/modules/zookeeper/manifests/server.pp#L94
=> Kafka: add zookeeper cleanup script

modules/mediawiki/templates/mediawiki-includes.conf.erb
=> Add some redirect exclusions for /w/index.php

modules/prometheus/manifests/exporter/cloudflare.pp
=> Cloudflare: re-eanble

modules/changeprop/templates/jobqueue.config.yaml.erb
From https://github.com/wikimedia/operations-deployment-charts/commit/3026d4164f28521d0b69e2154ceb19217651aa9d
=> changeprop: Add x-request-id header to jobqueue requests

hieradata/hosts/changeprop151.yaml, modules/changeprop/templates/initscripts/changeprop.systemd.erb, modules/changeprop/templates/jobqueue.config.yaml.erb
* Set UV_THREADPOOL_SIZE to 128
* Set PREQ_CONNECT_TIMEOUT to 60. Some how we need it?
* Unset disable_delayed_execution.
=> changejob: fix jobs processing speed

hieradata/hosts/changeprop151.yaml, manifests/site.pp, modules/haproxy/manifests/init.pp, modules/haproxy/manifests/site.pp, modules/haproxy/templates/haproxy.cfg.erb, modules/haproxy/templates/haproxy.default.erb, modules/role/manifests/jobrunner_haproxy.pp, modules/role/templates/jobrunner_haproxy/haproxy.cfg.erb, modules/role/templates/jobrunner_haproxy/haproxy.rsyslog.conf.erb, modules/role/templates/jobrunner_haproxy/lb.cfg.erb
Includes adding haproxy module which is from https://github.com/wikimedia/operations-puppet/tree/production/modules/haproxy. Minus the bits we don't want.
=> Add jobrunner_haproxy role

modules/role/files/kafka/kafka.sh, modules/role/manifests/kafka.pp
It's from https://github.com/wikimedia/operations-puppet/blob/8c2d6f688fd75980213cfa7cc01c3458b6baf902/modules/confluent/files/kafka/kafka.sh
It will make it easier for us as we don't use a apt package so it's installed in /opt.
=> kafka: Add kafka script

modules/role/manifests/db.pp
We migrated to systemd timer successfully.
=> db: remove unused cron

modules/base/templates/backups/wikitide-backup.py.erb
=> Revert "wikitide-backup: remove caching the token for now"

hieradata/role/common/mediawiki.yaml, hieradata/role/common/mediawiki_beta.yaml, hieradata/role/common/mediawiki_task.yaml
=> Revert "mediawiki: lower keep alive requests/timeout"

hieradata/hosts/mem151.yaml, hieradata/hosts/mem161.yaml
Lowers it to 62gb (59128 MiB).
=> mem161/mem151: lower memcache size

modules/mediawiki/templates/mediawiki-includes.conf.erb
=> Revert "T12621 - restrict what is considered a php file"

modules/mediawiki/templates/mediawiki-includes.conf.erb
Re-do of #4112 by @The-Voidwalker. The correct syntax is provided by @BlankEclair.
=> T12621 - restrict what is considered a php file

hieradata/hosts/cp36.yaml, hieradata/hosts/cp37.yaml, modules/varnish/manifests/init.pp
We increase cp37 to 5gb and keep cp36 at 1gb.
=> varnish: Set transient_storage manually

modules/monitoring/files/users.conf, modules/users/data/data.yaml
=> remove alex shell + icinga

modules/monitoring/files/scripts/mail-host-notification.sh, modules/monitoring/files/scripts/mail-service-notification.sh
Matches changes upstream although modifies slightly.
=> monitoring: Update mail-*-notification.sh scripts

modules/monitoring/files/bot/ircecho.py
Also use "." rather then index for args. In addition also cut down on unnecessary braces for print().
=> ircecho: use add_watch for WatchManager

modules/matomo/templates/config.ini.php.erb
=> matomo: unset enable_sql_optimize_queries

modules/mediawiki/templates/mediawiki-includes.conf.erb
=> T13127: Add query parameters for /wiki -> /wiki/ redirect

hieradata/hosts/cp36.yaml, hieradata/hosts/cp37.yaml, modules/nginx/manifests/init.pp, modules/nginx/templates/logrotate.erb
additionally run logrotate hourly to ensure minimal buildup
=> add maxsize to nginx logrotate

modules/role/manifests/cloud.pp
=> Revert "Temp allow cloud ssh without bastion"

modules/mariadb/templates/config/mw.cnf.erb
=> Revert "mariadb: default to read_only on startup"

modules/role/manifests/cloud.pp
=> Revert "Revert "Temp allow cloud ssh without bastion""

modules/mariadb/templates/config/mw.cnf.erb
=> Revert "Revert "Revert "mariadb: default to read_only on startup"""

modules/role/manifests/cloud.pp
=> Revert "Revert "Revert "Temp allow cloud ssh without bastion"""

modules/mediawiki/files/bin/mwdeploy.py, modules/mediawiki/manifests/jobqueue/runner.pp, modules/salt/files/bin/rename-wiki.py
Needed for miraheze/CreateWiki#695
=> Update CreateWiki maintenance scripts format

modules/mediawiki/manifests/jobqueue/runner.pp
Reverts miraheze/puppet#4242
Issues are fixed
=> Revert "mediawiki::jobqueue::runer: remove managewikis systemd timer for now"

modules/mediawiki/files/bin/backupwikis, modules/mediawiki/files/bin/mwdeploy.py, modules/mediawiki/files/bin/mwscript.py, modules/mediawiki/files/bin/test_mwscript.py, modules/mediawiki/manifests/jobqueue/runner.pp
Needed for miraheze/MirahezeMagic#554
=> Update MirahezeMagic maintenance scripts format

modules/ssl/files/nginx.conf, modules/varnish/templates/mediawiki.conf.erb
=> T12604: Add support for /.well-known/change-password

modules/irc/manifests/ircrcbot.pp, modules/irc/templates/initscripts/ircrcbot.systemd.erb, modules/role/manifests/irc.pp
might reduce lag, it seems to be hitting to 1 msg/s rate limit
=> irc: allow us to split the RC bot

modules/varnish/templates/default.vcl
Brings in some of the changes done in [0].
[0] https://gerrit.wikimedia.org/r/c/operations/puppet/+/1113592
=> varnish: some varnish 7 updates to templates

modules/varnish/templates/default.vcl
Copys [0] and [1].
[0] https://gerrit.wikimedia.org/r/c/operations/puppet/+/1029570
[1] https://gerrit.wikimedia.org/r/c/operations/puppet/+/1029614
=> Disable chrome private prefetch in varnish

modules/mediawiki/templates/mediawiki-includes.conf.erb
=> T13404: Do not redirect for /w/index.php?action=render

hieradata/role/common/mediawiki_task.yaml
So 12 * 1.5 = 18 rather then 12 * 2.0 = 24.
=> mediawiki_task: lower fpm_workers_multiplier to 1.5

hieradata/hosts/cp36.yaml
Use how many cores the server has (4)
=> cp36: unset nginx worker_process config

modules/base/templates/rsyslog/remote_syslog.conf.erb, modules/base/templates/rsyslog/remote_syslog_rule.conf.erb, modules/base/templates/rsyslog/remote_syslog_rule_parse_json.conf.erb, modules/grafana/templates/ldap.toml.erb, modules/mariadb/manifests/config.pp, modules/mariadb/manifests/instance.pp, modules/mariadb/templates/config/mw.cnf.erb, modules/postgresql/templates/ssl.conf.erb, modules/prometheus/templates/initscripts/prometheus-es-exporter.systemd_override.erb, modules/role/manifests/openldap.pp
I ran 
> [rhinos@test151:/etc/ssl/certs]$ diff LetsEncrypt.crt ISRG_Root_X1.pem
> [rhinos@test151:/etc/ssl/certs]$ 
and it's the same file
=> Replace LetsEncrypt.crt with ISRG_Root_X1.pem

hieradata/role/common/mediawiki.yaml
=> mediawiki: lower mediawiki::php::fpm::fpm_workers_multiplier to 1.5

modules/users/data/data.yaml
As above, add a new SSH key for myself
=> Add new SSH Key for myself

modules/users/data/data.yaml
=> users: promote somerandomdev

modules/base/manifests/firewall.pp, modules/monitoring/manifests/hosts.pp, modules/prometheus/manifests/exporter/node.pp, modules/prometheus/manifests/exporter/varnish.pp, modules/role/manifests/bastion.pp, modules/role/manifests/burrow.pp, modules/role/manifests/cache/cache.pp, modules/role/manifests/cache/haproxy.pp, modules/role/manifests/graylog.pp, modules/role/manifests/matomo.pp, modules/role/manifests/mattermost.pp, modules/role/manifests/mediawiki.pp, modules/role/manifests/mediawiki_beta.pp, modules/role/manifests/mediawiki_task.pp, modules/role/manifests/phorge.pp, modules/role/manifests/prometheus.pp, modules/role/manifests/swift.pp, modules/role/manifests/varnish.pp
=> Remove he-ipv6 checks

modules/users/data/data.yaml
=> access: add skye to test-admins

modules/users/data/data.yaml
Reverts miraheze/puppet#4437
I forgot to confirm something.
=> Revert "access: add skye to test-admins"

modules/puppetdb/manifests/init.pp
=> Revert "puppetdb: fix location to puppetdb-backup puppetdb.log for monitoring"

modules/users/data/data.yaml
=> users: promote skye

modules/mariadb/templates/config/mw.cnf.erb
=> Revert "mariadb: set default character set/collation"

hieradata/common.yaml, hieradata/hosts/dns001.yaml, hieradata/hosts/mattermost001.yaml, hieradata/hosts/mattermost1.yaml, hieradata/hosts/ns2.yaml, hieradata/role/common/bastion.yaml, modules/base/manifests/init.pp, modules/base/manifests/monitoring.pp, modules/role/manifests/bastion.pp
=> T14165: allow ntp to connect from internal network

modules/mediawiki/templates/mediawiki.conf.erb
To unify donations to one spot and not have to maintain this in landing. Will also redirect it.
=> Remove donate.miraheze.org
