miraheze/puppet

modules/parsoid/files/settings.js
For miraheze/mw-config#206, ref: miraheze/puppet#29.
=> Add parsoid conf for walthamstowlabourwiki.

modules/mediawiki/files/nginx/mediawiki.conf, modules/mediawiki/manifests/init.pp, modules/varnish/files/nginx/mediawiki.conf, modules/varnish/manifests/init.pp
Please double check for me before/after merging:
- paths to ssl_cert, key, and trusted cert (wild guess on all three)
- line 88, I'm not 100% sure that I don't want a slash between ```boulderwiki.org``` and ```$request_uri```
=> Propose to serve boulderwiki.org directly

modules/parsoid/manifests/init.pp
Note that the db name is teleswikiwiki and the domain is teleswiki.mh.o so this is correct
=> add parsoid for teleswikiwiki

modules/phabricator/data/config.yaml
For the backwards compatibility (GitHub) setting this for legacy support.
@JohnFLewis @Southparkfan opinions? (labster said 'maybe'.)
=> Add new keywords for commit resolver

modules/varnish/templates/mediawiki.conf
Possible fix for T581
Adding 301 redirect from www.thinkingliquid.org to thinkingliquid.org, guessed SSL cert locations based on pattern, filed alphabetically.
Please review this and prepare to roll back
=> Possible fix for T581

modules/varnish/templates/default.vcl
Reverts miraheze/puppet#222
Probable cause of 502's on meta and other wikis.
=> Revert "redirect Requests_for_adoption because of stupid sitenotice mistake t…"

modules/mediawiki/manifests/init.pp
Reverts miraheze/puppet#265
There are no issues with the change - the skin does not ignore the composer-driven files.
=> Revert "add refreshed skin composer configuration"

hieradata/common.yaml, hieradata/hosts/mw2.yaml, modules/mediawiki/manifests/dumps.pp, modules/mediawiki/manifests/init.pp
Puppet class and implementation to make mw2 export static dumps of select wikis.
=> mediawiki::dumps implementation

modules/phabricator/data/config.yaml
Ref [T1487](https://phabricator.miraheze.org/T1487). The user need to verify their email to get their email. It also shows black dots if email is not verified. Enforcing email verification requires additional steps for users but it makes sure user is notified of the change on the ticket.
=> Require email verification

modules/postfix/files/aliases
not sure how useful it is but if a lock is made by a CVT it should probably be discussed with them as well (not only with stewards)
=> add CVT email

modules/phabricator/data/config.yaml
there are a few tasks (such as upstream) where there is virtually nothing Miraheze can do. There are also other tasks that would fit into stalled, but those are the main ones.
=> add "Stalled" option

modules/mariadb/manifests/config.pp, modules/mariadb/templates/config/root.my.cnf.erb
With the renew, the SSL cert on db2 won't be valid anymore.
db3 doesn't have the cert at all.
Will reduce noise on db3 in regards to SSL and prevent noise on db2 about an invalid certificate soon.
[MERGE ONLY NECESSARY] Services will not be restarted as root.my.cnf is a my.cnf in /root/ and is not used at all by MariaDB.
=> Pull SSL cert on MariaDB

modules/postfix/files/aliases
Discussed a bit in -staff with labster. I think that it is better (and more professional) if all staff have a @miraheze.org alias. It's currently a bit confusing that 3 sysadmins do have one, and 3 sysadmins don't.
=> @miraheze.org alias for all staff

modules/mediawiki/manifests/init.pp
Per https://phabricator.miraheze.org/T1923#39573, since the servers have evolved there's a chance it won't OOM anymore
=> re-attempt to chown /srv/mediawiki/*

modules/phabricator/data/config.yaml
=> add transaction icon for stalled status on phab

hieradata/hosts/mw1.yaml, hieradata/hosts/mw2.yaml, hieradata/hosts/test1.yaml
Since /srv/mediawiki/config is now owned by www-data and most logs are
readable (if not they can be defined) I see no current use for keeping
the mw-roots group.
=> deprecate mediawiki-roots group

modules/mediawiki/files/jobrunner/check_jobqueue
We're getting many critical messages due to the jobqueue being over 250 many times. Since last time this was updated, we've expanded so it's normal to see more jobs.
=> increase jobqueue threshold to 300

modules/mediawiki/manifests/init.pp
Needed for an extension (T2142), and could be a possible fix (or at least attempt for T1813).
=> install lilypond package

modules/mediawiki/manifests/dumps.pp
Export scruffywiki images weekly is there twice (since both mine and the users PRs got merged, instead of just one). 
Causing mw2 puppet fail, please merge ASAP @NDKilla
=> remove double declaration of variable

hieradata/hosts/test1.yaml, manifests/site.pp, modules/puppetmaster/manifests/init.pp, modules/puppetmaster/templates/puppet.conf
The intention for this is to allow us to convert a test host into a puppetmaster to test some upcoming upgrades
=> Support using different puppet master host names

modules/git/manifests/clone.pp
In puppet 3 an empty string returned false, in puppet 4 it returns true, so lets set it to false explicity.
=> Set ssh to false (was empty string)

modules/git/manifests/clone.pp
Puppet 3 empty strings returned false, in puppet 4 they return true.
=> Fix more empty strings

modules/puppetdb/manifests/database.pp
For now doing this on the command like will fail as it needs the user and password. But i am not sure how to do this as on the command line it will do a password prompt, but that won't work if you are doing it through puppet.
Maybe we will have to in the future at some point create a user that dosen't require a password that is a super user?
=> Cross out database and user creation

modules/role/manifests/postgresql.pp
This will be used by db4 to host puppetdb database.
=> Create postgresql role

modules/ssl/manifests/wildcard.pp
This fixes an issue where it try to add the file again leading to puppet errors as you carn't do the same thing twice.
=> Change !defined to defined

modules/nginx/manifests/init.pp
This is so nginx will install on jessie and stretch or any other debian os.
=> Use ${::lsbdistcodename} for apt::source nginx apt package

modules/dns/manifests/init.pp
No need to add this on stretch as it would have this already and also may cause apt problems since it could be duplicating things causing update problems.
=> Only add stretch apt repo if on jessie for dns

modules/icinga/manifests/init.pp, modules/phabricator/manifests/init.pp, modules/phabricator/templates/php72.ini.erb
Phabricator requires php5 or php 7.1+.
Php 7.0 is not supported.
=> Add support for php 7.2+ in icinga and phabricator class

modules/icinga/manifests/init.pp, modules/phabricator/manifests/init.pp, modules/php/manifests/init.pp
This should only be used with phabricator and icinga for now.
With plans to roll this out to other modules at later dates.
=> Add php module that installs php 7.2 on stretch and 5 on jessie

modules/postgresql/files/ssl.conf, modules/postgresql/manifests/server.pp
there is permission errors when using the one from /etc/ssl so lets just fix this by adding it to postgresql dir.
=> Add wildcard.miraheze.org.key key to postgresql ssl dir

modules/ssh/templates/sshd_config.erb
OpenSSH the version in stretch disables dsa by default for security reasons.
=> Remove loading ssh_host_dsa_key

manifests/site.pp, modules/restbase/files/miraheze_project.yaml, modules/restbase/templates/config.yaml.erb
Now that we have mathoid on mw* locally we doin't need it running on misc3 aswell.
=> Remove mathoid from misc3

README.md
This link is dead - I’m not sure if it has been relocated elsewhere or what, but having a dead link in the main README for an entire repo probably isn’t the best thing in the world.
=> Remove dead link T3645

modules/bacula/templates/director/bacula-dir.conf
Changes done in this patch:
* No longer backup the lizardfs master because if we need to restore everything because of corruption it's best to do it on a fresh master.
* No longer backup the lizardfs* /var/lib/lizardfs as it's pointless not much in there.
* Only backup /mnt/mediawiki-static on lizardfs1 so we can restore individual files.
=> Backup /mnt/mediawiki-static from lizardfs1

modules/salt/manifests/apt.pp, modules/salt/manifests/master.pp, modules/salt/manifests/minion.pp
This is to install the latest salt from upstream (as the one from debian is broken)
=> Add Salt apt puppet class

modules/base/files/environment/vimrc.local, modules/base/manifests/init.pp
Will fix vim so we can copy text without having to do ":set mouse=r"
=> Add vimrc.local to /etc/vim/vimrc.local

modules/phabricator/manifests/init.pp
- use a full URI to an avatar that should not change
- then we can stop expecting a 500
- expect to get "HTTP/2 200" (what i get when testing with curl), actually HTTP/2  not 1.1 (wow?)
=> fix monitoring check for phab.miraheze.wiki

modules/mediawiki/templates/jobrunner.json.erb
This may help alleviate the problem with the jobrunner when for example "LocalGlobalUserPageCacheUpdateJob" piles up. The job runner will be able to process other jobs too thus won't be stuck on LocalGlobalUserPageCacheUpdateJob.
Also increase memory to 200M
=> jobrunner: Split some jobs out so it has a dedicated process for that job

modules/monitoring/manifests/hosts.pp
In #951 support for openvz containers was added where you have to use a custom fact to get the virtual IP address. This removed support for regular non-containers though where the regular ipaddress fact should be used. Make the module flexible to support both.
=> make host monitoring work also on non-containers again

modules/monitoring/manifests/hosts.pp, modules/role/manifests/icinga2.pp
fix the syntax errors spotted by Papaul and actually include the class in the Icinga role
=> include profile::wiki_monitoring and fix syntax errors

modules/bacula/templates/director/bacula-dir.conf
This spreads db4 so that it's 5x80 (5gb each file)
Same for static 5x50 (5gb each file)
=> Spread backups across multiple files

modules/nginx/templates/nginx.conf.erb, modules/varnish/templates/mediawiki.conf
This reduces it to below php-fpm in the hopes that php-fpm won't kill the process.
=> Reduce nginx timeout to 220

modules/users/manifests/hashuser.pp, modules/users/manifests/user.pp
Also fixes puppet type for gid field. (Changes it to an Integer)
Bug: T4410
=> Users: Add missing 'gid' param

modules/base/templates/icinga/nrpe.cfg.erb
This makes sure to only report a critical if only there's 5% of the disk left or a warning if only 10% is left.
=> Reduce check_disk to check for 5% left of the disk

modules/mediawiki/manifests/jobrunner.pp
It currently does not work and is causing a ton of exceptions in mw3 log.
=> jobrunner: Temporarily remove monitoring for JobQueue

modules/prometheus/manifests/init.pp, modules/prometheus/templates/prometheus.yml.erb
it was monitoring hosts that didn't have php-fpm installed.
=> prometheus: Fix prometheus mentoring php-fpm

hieradata/hosts/cp2.yaml, hieradata/hosts/cp3.yaml, hieradata/hosts/cp4.yaml, hieradata/hosts/mw1.yaml, hieradata/hosts/mw2.yaml, hieradata/hosts/mw3.yaml, modules/nginx/manifests/init.pp, modules/nginx/templates/nginx.conf.erb
Here's what's included:
* cp* set nginx::worker_processes to 4.
* mw* set nginx::worker_processes to 8.
* Reduce keep alive to 30. It was way to high. We doin't want to keep the connection to the same server for too long.
=> nginx: Introduce nginx_worker_processes with the default set at auto

modules/gluster/files/secure-access, modules/gluster/manifests/init.pp, modules/gluster/manifests/mount.pp
What this does is:
* Sets ssl certificate, CA and private key instead of using a default file.
* Sets ssl-cert-depth to 2.
=> gluster: Add secure-access file

hieradata/hosts/lizardfs6.yaml, modules/mediawiki/manifests/php.pp
Also increase fpm_min_restart_threshold to 32 for lizardfs6
=> mediawiki: Make fpm_min_restart_threshold configurable

modules/mariadb/templates/config/mw.cnf.erb
Also adjust configs (which is from https://github.com/wikimedia/puppet/blob/production/modules/role/templates/mariadb/mysqld_config/production.my.cnf.erb)
=> mariadb: Switch on threads pool

modules/mediawiki/templates/mediawiki.conf
per request on discord, where such files are uploaded to csydeswiki but cannot be used until such change is made
=> Add Access-Control-Allow-Origin to sfnt (font) files

modules/mediawiki/templates/mediawiki.conf, modules/nginx/templates/nginx.conf.erb
Setting headers in the local {} block, will prevent the global headers from taking effect. We have to add the global headers in the local {} block for it to take effect again.
Also switch off server_tokens.
=> mediawiki: Add global headers to local {}

modules/mediawiki/manifests/jobrunner.pp
Based on https://github.com/wikimedia/puppet/blob/b347052863d4d2e87b37d6c2d9f44f833cfd9dc2/modules/mediawiki/manifests/maintenance/initsitestats.pp#L2
Bug: T4312
=> Run update_statistics cron on the 1st and 15th of each month

modules/varnish/files/stunnel/stunnel.conf, modules/varnish/templates/default.vcl
(this can only be used with headers set)
=> Add test2 to varnish

modules/varnish/templates/default.vcl
They cause the site to be slow due to the long distance to db4.
=> varnish: Remove mw[4567]

modules/grafana/templates/grafana.ini.erb
Only allow admins to create accounts.
=> Grafana: Set allow_sign_up to false

modules/postfix/files/aliases
That was still there? Long month!
https://bash.toolforge.org/quip/AU7VTzhg6snAnmqnK_pc
=> Remove “temp” redirect to my personal email

modules/php/manifests/init.pp, modules/php/manifests/php_fpm.pp
Due to a bug, we will be forcing usage of debian's repo which has 7.3.14.
=> php: Do not use sury php apt repo on 7.3

modules/base/files/apt/50unattended-upgrades
Today this caused an outage on mw[4567] when php-redis was upgraded.
=> apt: Blacklist php unintended upgrades

modules/varnish/templates/default.vcl
The new infrastructure seems better and latency decreases.
=> cp7: Check allthetropeswiki instead of loginwiki temporarily

modules/base/manifests/arcanist.pp, modules/phabricator/manifests/init.pp
No longer needed in recent updates (its been emptied).
=> Remove installing libphutil

modules/irc/manifests/ircrcbot.pp
Bot keeps flooding out and ideally we shouldn’t be sending more than 1 message every 2 seconds. Try upping to 1s sleep as I don’t think we’ll have any issues with that.
=> up sleep time to 1

modules/monitoring/files/services.conf, modules/monitoring/manifests/init.pp
Set these vars:
```
vars.ping_wrta = 500
vars.ping_wpl = 20
vars.ping_crta = 2000
vars.ping_cpl = 100
```
This means we up when we alert to 500ms+ (warning) and 2000ms (critical).
Packet loss is 20% (warning) and 100% (critical).
Defaults are:
```
vars.ping_wrta = 100
vars.ping_wpl = 5
vars.ping_crta = 200
vars.ping_cpl = 15
```
=> monitoring: Increase ping critical/warning levels

modules/monitoring/files/groups.conf
This means we won't have to update this frequently to new hosts added.
=> monitoring: Update groups checks to use match()

modules/bacula/manifests/director.pp
Remove firewall for 9101/9103 (bacula uses localhost so no firewall is needed for those ports yet).
9102 will be limited to servers that have the bacula client class installed.
=> bacula: Overhaul firewall rules

modules/profile/manifests/openldap.pp
Creates an admin group. A admin account will be setup, separate to the one setup as the default.
=> openldap: redo access permissions

manifests/site.pp
Since mysql is still running, changing this now won't affect anything.
=> Switch db13 to the db role

modules/mediawiki/manifests/jobrunner.pp
This populates static.miraheze.org/sitemaps/sitemap.xml with an index of all sitemaps. It runs 24 hours after the sitemap script for each wiki to ensure that has finished.
=> Add generateSitemapIndex script

modules/base/files/apt/50unattended-upgrades
Redis broke because we use a different systemd unit (e.g it overwrote our unit).
=> base: Do not run unintended upgrades for redis

modules/mediawiki/manifests/jobrunner.pp
We don't seem to run this, it "Also update[s] active users count."
=> jobrunner: add --active to initSiteStats cron

modules/mediawiki/manifests/packages.pp
Per https://gerrit.wikimedia.org/r/c/operations/puppet/+/612274/2/modules/mediawiki/manifests/packages.pp and https://phabricator.wikimedia.org/T248418#6351818
This already off for all Miraheze Wikis.
=> MediaWiki-packages: drop lillypond

modules/mediawiki/manifests/monitoring.pp, modules/monitoring/files/commands.conf
We want to use -I so that the check, checks the individual servers. -s is a string match which we don't want (which didn't work for us anyways as host.address was returning as a string)
=> monitoring: Fix check_mediawiki command

modules/mediawiki/templates/mediawiki-includes.conf.erb
Due location ^~ /wiki {, it was matching urls like https://wiki.climatechange.ai/wiki.climatechange.ai/v1/?spec which meant it proxied through php-fpm rather than rest base. We fix this to ensure that just because the url contains wiki., it doesn't proxy through php-fpm.
=> mediawiki: Fix proxying through rest base

modules/mediawiki/templates/jobrunner.json.erb
Per @Southparkfan, we are over utilising, so going to reduce some of the pressure by lowering the amount of runners.
=> jobrunner: Reduce runners to 2

modules/varnish/manifests/nginx.pp, modules/varnish/templates/mediawiki.conf
* Whitelist all of Miraheze ips
* Do not rate limit static.miraheze.org as it can handle the traffic
=> varnish: Fix rate limiter

modules/varnish/templates/mediawiki.conf
* Increase rate limiting to 30r/s.
* Increase bursts to 20.
* Use nodelay (reference https://www.nginx.com/blog/rate-limiting-nginx/#Queueing-with-No-Delay).
* Introduces a static rate limiter allowing up to 300 requests a second with a burst of up to 200.
=> varnish: Change rate limit rules

modules/base/templates/icinga/nrpe.cfg.erb, modules/gluster/manifests/init.pp
The port changes when you restart the services, so is better to monitor by service.
=> gluster: Monitor the service rather than the port

modules/varnish/data/frame_whitelist.yaml
the frame whitelist allows external domains to frame Miraheze, not allowing Miraheze wikis to frame them, therefore these should not be whitelisted here.
=> Remove non-*.miraheze.org domains from frame_whitelist

modules/mediawiki/manifests/cron.pp
It has been absented for quite a while so is safe to remove now.
=> Remove update_database_lists cron

modules/mediawiki/templates/mediawiki.conf.erb
Some wikis contained private in their name so fix this by adding a slash.
=> mediawiki: Fix private location

modules/mediawiki/manifests/init.pp
Should speed things up, and also use less disk space
=> mediawiki: Change git clone depth for cloning core to 1

modules/varnish/templates/default.vcl
The reason is static can handle much more without issues. So 120 over 10s was little especially for static which can handle even more than 500 but I think 500 is a good in between number in the meantime till I get @Southparkfan thoughts.
=> varnish: Increase rate limit for static to 500/1s

hieradata/hosts/cloud1.yaml, hieradata/hosts/cloud2.yaml, hieradata/hosts/cloud3.yaml, hieradata/hosts/cloud4.yaml, hieradata/hosts/cloud5.yaml
We need to log locally because incase of failures, it may not log to graylog.
This is to be on the safe side.
=> cloud: Do not use syslog_ng

modules/mediawiki/templates/mediawiki-includes.conf.erb, modules/mediawiki/templates/mediawiki.conf.erb, modules/varnish/templates/default.vcl
We also set it for all files hosted on static.miraheze.org.
Bug: T6730
=> varnish: Centralise Access-Control-Allow-Origin header

modules/irc/files/logbot/adminlog.py
I ran a few tests and this seems to work.
This is so {{TOCRIGHT}} doesn't end up being stuck at a random part of the page.
Replaces #1664 by @dmehus
=> adminlog: maintain text above the first header

modules/irc/files/logbot/adminlog.py
Reverts miraheze/puppet#1665
Per Doug. This doesn't take wikilinks into account.
=> Revert "Wrap SAL entries with <nowiki></nowiki>"

modules/mediawiki/templates/mediawiki.conf.erb
=> mediawiki: Add expires field to static.miraheze.org location

modules/varnish/manifests/init.pp
This isn't producing interesting logs that we want, so we can stop this. This will reduce disk space issues.
=> varnish: Stop varnishncsa service

modules/mediawiki/templates/mediawiki.conf.erb
Props to @Universal-Omega and @paladox for telling me which file to edit. Could also make the target https://meta.miraheze.org/wiki/Donate, but this seems reasonable, based on my discussions with Omega
=> Create web redirect for /donate, per suggestion of RobLa on Discord

modules/gluster/manifests/init.pp, modules/gluster/manifests/mount.pp
This is not needed as we set a different a different path to our certificate.
=> gluster: Remove gluster.[pem|key|ca] file

modules/users/manifests/user.pp
the function was deprecated as of puppet 5
=> users: remove usage of the deprecated function is_array

modules/mediawiki/manifests/init.pp
To hopefully fix puppet timeouts
=> set depth to 1 instead of 5 for cloning core

modules/irc/templates/logbot/config.py
Reverts miraheze/puppet#1757
Quoting John from 2018 heh, but just figured this out:
[2018-07-03 02:48:46] <JohnLewis> paladox: for some reason, only having 1 channel causes the logbot to fail to join
[2018-07-03 02:48:55] <JohnLewis> which may explain why I left it like that intentionally
=> Revert "MirahezeLogbot: Don't join #miraheze-sre-security"

modules/mediawiki/files/mwscript.py
Just as a precaution if someone did it would log the information its supposed to remove.
Alternatively we could do something like (possibly not exact but likely similar):
```python3
if scriptsplit[2] != "removePII.php":
os.system(logcommand)
```
Feel free to close if really unnecessary.
=> Don't allow RemovePII to ever be ran with mwscript

modules/mediawiki/files/bin/mwscript.py
We should consider for long running scripts to log START too. (imports, foreachwikiindblist etc.)
=> mwscript: note logging is for end -  pass return code

modules/mediawiki/manifests/packages.pp
Reverts 1045deb593d130fe92aa47f721bd7e44c0b139c5
We need various other stuff setup as well before the extension can come back but soon!
=> mediawiki::packages: reinstall lillypond

hieradata/hosts/jobrunner3.yaml, hieradata/hosts/jobrunner4.yaml
Much safer to run on jobrunner4, which has no critical processes
=> jobrunner3 cannot run intensive jobs

hieradata/hosts/jobrunner3.yaml, hieradata/hosts/jobrunner4.yaml, hieradata/hosts/mw10.yaml, hieradata/hosts/mw11.yaml, hieradata/hosts/mw9.yaml, hieradata/hosts/test3.yaml
To reduce load, this starts running puppet at 1,31 on test3 then proceeds down mw*,jobrunner* every minute alternating between cloud servers. This should reduce the chance of high load on things.
=> puppet: rebalance MediaWiki puppet times 

hieradata/common.yaml, hieradata/hosts/mw10.yaml, hieradata/hosts/mw11.yaml, hieradata/hosts/test3.yaml
This means:
- by default, install the ssh key for www-data syncing and do not be a staging/canary server
- On test3, don't install the www-data key / be a staging server so it has the git clone but only skip syncing to other servers (/srv/mediawiki locally will still be setup and come from the local staging folder)
- On mw10, (this is random but it's a server and the 8/9 struggle more with load) install staging and canary (this means it will have the public & private key pair for access in a deploy keys folder and armed in ssh agent. Do not allow remote access using the ssh keys. By default, sync files from the deploy command to all mediawiki servers except test3
=> hieradata: set values for sync scripts

modules/mediawiki/manifests/extensionsetup.pp
we only use this for reclones and the file perms on cache files are funky
=> extsetup: don't cache composer on staging

modules/varnish/templates/initscripts/varnish.systemd.erb
KillMode of process is not recommended as it silently kills the process but allows it to continue running unaware to system.d. In essence, this means an OOM killer would 'kill' a sub process, not trigger the master service to be killed and consequently keep running broken until restarted manually.
=> T7319: Change KillMode to control-group for Varnish

modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/PrivateSettings.php
This can be done just in LocalSettings.php, since the site key is not private, only the 'secret' key is 'secret'
=> Remove $wgReCaptchaSiteKey from PrivateSettings

hieradata/hosts/db11.yaml, hieradata/hosts/db12.yaml, hieradata/hosts/db13.yaml, modules/mariadb/manifests/config.pp
Also prevent creating /tmp if the tmpdir variable is set at /tmp.
/srv/tmp was causing mariadb to show "2021-08-19 16:53:18 0 [Note] mysqld: O_TMPFILE is not supported on /srv/tmp (disabling future attempts)" in the logs.
=> mariadb: Change all the dbs to use /tmp rather then /srv/tmp

hieradata/hosts/db11.yaml, hieradata/hosts/db12.yaml, hieradata/hosts/db13.yaml
This is being done as both are OOM'g and reading up on the docs the benefit of the buffer pool are undone when swapping which each server is doing.
=> db11/12/13: Change buffer pool instance to one including size

modules/php/manifests/php_fpm.pp
php7.xxx-apcu is a virtual package. We don't need that.
=> php: Only install php-apcu rather then the versioned one

modules/varnish/manifests/init.pp, modules/varnish/templates/initscripts/varnish.systemd.erb
If cores is 1 x 250 which equals to 250 lets just make it 500.
Varnish default is 500 anyways.
=> varnish: Set max threads to at least 500+

hieradata/hosts/mw10.yaml, hieradata/hosts/mw11.yaml, hieradata/hosts/mw12.yaml, hieradata/hosts/mw13.yaml
This is to prevent puppet3 being overloaded which would lead to unexpected consequences on mw* leading to higher load/user impact.
=> slightly adjust mw10/11/12/13 puppet run times

hieradata/hosts/cp12.yaml
We don't need to set it to 4. We use a NVME now so I/O isn't much of an issue.
=> cp12: Unset nginx::worker_processes

modules/varnish/data/csp.yaml
Already in `img-src` so adding to `script-src` also.
I could not find a review task for this though. This can be a temporary measure until it's CSP is fully approved. It is possible I just missed the review task or it was missed during the mass creating of tasks.
=> CSP: add scratchblocks.github.io to `script-src` (T8002)

modules/varnish/data/csp.yaml
This is needed by the Cargo extension to display OpenLayers maps
=> CSP: add openlayers.org to `script-src`

modules/mediawiki/manifests/packages.pp
Since python the package is no longer available which installed python-minimal which did the work of making sure "python" was available. We manually install python3-minimal which does this work.
=> mediawiki: Install python3-minimal

modules/mediawiki/files/bin/mwscript.py
It's never used. It makes sense for this to just be a comparison on `all` and drop the `tuple` all together, since only `all` is really used, and is easier to use.
=> mwscript: drop option to use foreachwikiindblist

modules/mediawiki/manifests/php.pp
Currently it only effects fpm, this should effect CLI also if `use_tideways` is enabled, which it is on test3 only. This should allow using the `--profiler` command line option in maintenance scripts on test3.
After further looking at this, it appears to have not been used at all, so this actually uses `mediawiki::php::use_tideways`
=> Enable tideways for CLI

modules/users/files/home/southparkfan/.bash_aliases, modules/users/files/home/southparkfan/.vimrc
Since Southparkfan is no longer a member of SRE. In addition, the `.bash_aliases` would've been completely broken anyways.
=> Delete modules/users/files/home/southparkfan directory

modules/varnish/templates/default.vcl
Per suggestion from @Universal-Omega (see https://github.com/miraheze/puppet/pull/2107). 
The goal is to prohibit Google/Bing from uselessly indexing /w/index.php and causing clashes with articles indexed via /wiki/ in search engines.
=> Noindex for /w/index.php?*

modules/mediawiki/templates/mediawiki.conf.erb
The whole comment seems to be centered around restbase-lb, which was removed.
=> mediawiki.conf.erb: remove comment

modules/varnish/data/csp.yaml
To fix https://meta.miraheze.org/wiki/Stewards%27_noticeboard#Help,_embeded_content_not_working.
=> Add player.vimeo.com and docs.google.com to frame-src

modules/mediawiki/files/bin/deploy-mediawiki.py
Not certain this will fix it but currently deploys are not working except to mw11, to others it deploys to /srv/mediawiki/config/config or /srv/mediawiki/landing/landing for example. And the removal of the trailing slash was the only real difference in what commands are returned, that I could see.
=> fix deploy-mediawiki

modules/mediawiki/templates/mediawiki-includes.conf.erb
I'm not 100% sure this'll work, but did a bit of research and it might. Setting this to 1200 is the longest it value set in https://github.com/miraheze/mw-config/blob/7cf9810/LocalSettings.php#L8-L17, which should allow `set_time_limit` to properly work.
=> MediaWiki: fix timeouts

modules/mediawiki/files/bin/mwscript.py
* use argparse
* running scripts for specific extensions or skins is now done with `--extension` or `--skin` instead of input prompt
* maintenance script arguments are no longer required to be in quotations, all unknown arguments to mwscript are now used for the maintenance script arguments
* adds `--no-log` argument
* adds `--confirm` argument
* converts long scripts to a defined tuple, and adds support to add extension maintenance scripts to the tuple if it is necessary in the future
* adds `nukeNS.php` and `refreshLinks.php` to `longscripts`
=> mwscript: rewrite to use argparse

modules/varnish/templates/default.vcl
Hopefully will fix T7311
Always setting `Access-Control-Allow-Origin = "*"` for api.php is not good practice, as it allows unauthenticated requests to the API from anywhere (and for requests with `Access-Control-Allow-Credentials: true`, and `credentials: 'include'` this would be a security risk if the browsers did not block this). This removes that while attempting to maintain the hack for https://phabricator.wikimedia.org/T217669.
Currently, for example any API requests like `
```js
fetch('https://login.miraheze.org/w/api.php', {
mode: 'cors',
credentials: 'include'
})
```
will fail because `Access-Control-Allow-Origin = "*"` is being set which the browser will block for security reasons when `credentials: 'include'`. I am hoping this will resolve all of these issues, while still …
=> Handle CORS preflight requests + fix `Access-Control-Allow-Origin` for api.php

modules/varnish/templates/default.vcl
using `return(deliver)` should've made this work again without changing location, as it did before.
=> use `req.url` for undefined/api.php redirect again

modules/varnish/templates/default.vcl
* The `Content-Length` header results in 0 bytes being returned, therefore empty output.
* The `Connection` header is just unnecessary from what I can tell.
=> Remove `Content-Length` and `Connection` headers

modules/varnish/templates/default.vcl
This is exactly a duplicate of `mwtask1` backend, since there is no health check on the `mwtask1` backend.
=> Remove `mwtask1_test` backend

modules/mediawiki/files/robots.php
To avoid `BadMethodCallException: Sessions are disabled for this entry point in /srv/mediawiki/w/includes/session/SessionManager.php:849`
Should be set back to `1` once this becomes stable and does not warn anymore.
Also avoid using `ContentHandler::getContentText()`
=> robots.php: set `MW_NO_SESSION` to only warn

modules/base/manifests/syslog.pp
It made looking at the unit slower and also we didn't need a persistent journal.
=> base: If running bullseye or above remove /var/log/journal

modules/mediawiki/manifests/php.pp
1gb was way too high for the amount of ram we have.
=> mediawiki: Lower apc.shm_size to 256M

modules/php/manifests/fpm/pool.pp
The previous mitigations have reduced memory by quite a bit and limited the rate of OOMs but the graphs still aren't amazing.
Restarting an individual worker isn't much of an impact for user facing performance but it might help flatten the graphs a bit more and limit the leak even further. This should help us increase confidence in bullseye even if we haven't found the root cause and limit any impact of any issue which is always good.
=> php: drop max_requests by 50%

modules/base/manifests/puppet.pp
Bullseye isn't support for the server or db package yet so use the buster version for now.
=> base::puppet: Set release to buster

modules/mariadb/manifests/config.pp, modules/mariadb/templates/config/mw.cnf.erb
We are not using replication so this is unneeded.
=> mariadb: Remove server-id

modules/mediawiki/manifests/extensionsetup.pp
Otherwise it fails because somehow it's not falling back to ipv6? See https://npm.community/t/npm-fails-to-install-on-ipv6-only-networks/9508
=> Force registry.npmjs.org to use ipv6

modules/letsencrypt/files/mirahezerenewssl.py
This should work on both infrastructures since mwtask1 is also on bullseye/python3.9. This does require python3.8+ so wouldn't work on buster, which we are on python3.7 though.
From https://docs.python.org/3/library/logging.html#logging.basicConfig:
> If this keyword argument is specified as true, any existing handlers attached to the root logger are removed and closed, before carrying out the configuration as specified by the other arguments
It should prevent errors like FileNotFoundError in the future.
=> mirahezerenewssl: use force=True for logging

modules/base/manifests/packages.pp
This is to get extra features like ipv6 support
=> Install  netcat-openbsd globally

hieradata/hosts/mw101.yaml, hieradata/hosts/mw102.yaml, hieradata/hosts/mw111.yaml, hieradata/hosts/mw112.yaml, hieradata/hosts/mw121.yaml, hieradata/hosts/mw122.yaml, hieradata/hosts/mwtask111.yaml
Jobchron is now available.
This will only process jobs received from the new DC.
=> jobrunner: switch on new DC

modules/mariadb/templates/grants/default-grants.sql.erb
This is a new permission under 10.5.
=> mariadb: Grant REPLICA MONITOR to exporter on bullseye+

modules/mediawiki/templates/mediawiki.conf.erb
* miraheze/ErrorPages#3 creates the error page.
This is just so it looks neater then the default 502 error page which is just "502 Bad Gateway".
=> MediaWiki: add custom 502 error page for nginx

modules/mediawiki/files/bin/deploy-mediawiki.py
So it uses ovlon in logs if all is specified.
=> Overwrite server name with ovlon if all before running

modules/monitoring/files/check_reverse_dns.py
They use an ALIAS type instead which is fine. It's impossible to tell whether this is actually an A/AAAA record.
=> rdns: allow flat CNAME for dreamhost too

modules/varnish/templates/default.vcl
Thanks to a lot of magic, we can now switch simply by changing the backend.
=> [22:50] MediaWiki: Switchover to new infra

modules/imagemagick/files/policy.xml
=> ImageMagick: limit memory usage to 128MB

modules/varnish/templates/default.vcl
Shouldn't be necessary anymore, now that we utilise QuickInstantCommons.
=> Remove hack for T217669

modules/base/manifests/firewall.pp, modules/role/manifests/bastion.pp
Moves the bastion public ssh access firewall rule to the bastion role.
base::firewall should not set up firewall rules for individual services,
that responsibility should be left to the puppet modules configuring
those individual services.
Also clarify naming in the bastion role to make the names more clear.
=> bastion: move firewall rule to role class

.github/workflows/workflow.yml
This should only run on python files with this. 
Also, if we want to only enforce things in the MediaWiki module, we can do:
```yaml
paths:
- 'modules/mediawiki/**.py'
```
=> Only run workflow on python files

modules/varnish/templates/default.vcl
* Remove "If you're a wiki visitor or owner" — since that's all-inclusive and unnecessary.
* Fix some wording and capitalisation.
* Mention alternatives if Phabricator is also down. Since if the cache proxies are the issue, Phabricator will likely also be down as it's now behind the cache proxies.
=> Varnish: update 503 error message

modules/prometheus/manifests/class.pp
At some stage I think or rather guess maybe we should move to https://github.com/wikimedia/puppet/blob/production/modules/prometheus/manifests/class_config.pp
I'm not 100% sure on it hence why it's not being done now, but based on reading I guess it allows you to use anything define/class?
=> prometheus::class: support define

hieradata/common.yaml, hieradata/hosts/test101.yaml, modules/mediawiki/manifests/monitoring.pp
this is needed because currently the check fails for test101 because in all cases we are trying to check loginwiki, and test101 only serves the beta cluster, and thus cannot serve loginwiki causing the check to fail with 404. This makes it configurable per server. We default to loginwiki, and explicitly set betawiki for test101.
=> mediawiki: move monitoring host to to hiera

modules/mediawiki/templates/jobrunner.json.erb
It only was noticed on test101 and it's growing a huge backlog due to refreshLinks being on mwtask.
We should see if we can cope to avoid disaster.
=> jobrunner: allow mw* to manage RecordLint

modules/mediawiki/files/favicon.php, modules/mediawiki/files/robots.php, modules/mediawiki/files/sitemap.php, modules/mediawiki/files/touch.php, modules/mediawiki/manifests/favicons.pp, modules/mediawiki/manifests/init.pp, modules/mediawiki/templates/mediawiki-includes.conf.erb, modules/mediawiki/templates/mediawiki.conf.erb, modules/varnish/templates/default.vcl
* Allows static files to be accessed directly from the wiki subdomain or custom domain using /static.
* Should exclude private access, but this should be verified.
* Allows access to favicon/apple touch icon directly from /favicon.ico or /apple-touch-icon.png.
* Rewrites sitemap.php to use MediaWiki's HttpRequestFactory in order to retrieve the sitemap directly from static, rather than redirecting to it. This is designed to fix support for the sitemap index usage within Google, etc...
* Also provides better code standards rather than again decoding the database file, it uses WebStart, and then `$wgDBname` directly.
* Simplifies robots.php to use `$wgDBname` directly, rather than decoding the database file again. This should be accessible since we use WebStart.
* The use of WebStart for …
=> Allow static access from same domain

modules/varnish/templates/default.vcl, modules/varnish/templates/initscripts/varnish.systemd.erb
Limited testing showed that this at least fixed T8908.
Upstream had a similar issue [0] and was fixed with [1].
[0] https://phabricator.wikimedia.org/T266373
[1] https://gerrit.wikimedia.org/r/c/operations/puppet/+/641724/
Bug: T8908
=> varnish: Set large_objects_cutoff and nuke_limit

modules/varnish/templates/initscripts/varnish.systemd.erb
listen_depth default is 1024 but we have net.core.somaxconn set to 4096. Lets set varnish to 4096 as well.
=> varnish: match listen_depth and net.core.somaxconn

modules/varnish/templates/default.vcl
Whilst increasing nuke_limit helped a bit, we still had the problem sometimes.
Setting the large_objects_cutoff to 8mb means objects over this won't get cached (and thus won't hit this problem), this is only for static.miraheze.org.
We could set nuke_limit to a big number but based on our little storage space we're giving to varnish + we have over 5k wikis, I think it's better to just lower the large object cut off.
I was reading https://phabricator.wikimedia.org/T266373#6630349 which also went over increasing nuke_limit to something like 9999999 but went onto explain it could cause other issues.
I also think it makes sense not to cache large objects so we save space to cache more objects.
Bug: T8908
=> varnish: lower large_objects_cutoff to 8388608 (8mb) for static.miraheze.org

modules/varnish/templates/initscripts/varnish.systemd.erb
From the documentation:
- The TTL assigned to objects if neither the backend nor the VCL code assigns one.
The WMF set this at 24h but I don't think we should do 24h yet so instead the best value is 1 hour.
=> varnish: increase default_ttl to an hour from 2 minutes

modules/varnish/templates/mediawiki.conf
Lets have nginx synchronously deliver the response instantly.
See https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
=> varnish: set proxy_buffering to off in nginx config

modules/nginx/templates/nginx.conf.erb, modules/varnish/templates/default.vcl
It's recommended here [0] to do it in varnish rather than the web server as it'll use less cpu resources.
[0] https://varnish-cache.org/docs/trunk/users-guide/compression.html#compressing-content-if-backends-don-t
=> varnish: do gziping in varnish rather than varnish

modules/php/manifests/php_fpm.pp
=> Raise `request_terminate_timeout` to 60 instead of 59

modules/php/manifests/init.pp
Also removes unneeded `requires_os`
=> PHP: set base `memory_limit` to 100MB

modules/mediawiki/templates/jobrunner.json.erb
stops a single type using up all resources, done upstream and advised by Krinkle yesterday
=> jobrunner: set maxjobs to 1

hieradata/common.yaml, modules/base/manifests/monitoring.pp
Seems to be unused and the puppetmaster module was removed with e694825.
=> Remove `puppetmaster` from hieradata

modules/mediawiki/templates/jobrunner.json.erb
It would just be running the same thing twice: https://github.com/miraheze/jobrunner-service/blob/58a49a34c11f2fdddb701f1d296928779c1c0e7a/redisJobChronService#L92 I don't think we want to do that.
=> jobrunner: don't set server twice in redis.queues

manifests/site.pp, modules/letsencrypt/manifests/web.pp, modules/phabricator/files/phab.miraheze.wiki.conf, modules/users/data/data.yaml, modules/varnish/templates/default.vcl
Note: removes this from phab.miraheze.wiki because it is theoretically unnecessary, to be there at all:
```nginx
location /.well-known/acme-challenge/ {
rewrite ^/(.*)$ http://mwtask.miraheze.org/$1 redirect;
}
```
So I did not move it over, since I don't think it's necessary anymore. I could be wrong though. If so, we could always add it back next time the domain is attempted to be renewed I guess? If wanted I guess I can add it back.
=> Remove LetsEncrypt from mwtask111

modules/mediawiki/templates/mediawiki-includes.conf.erb, modules/mediawiki/templates/mediawiki.conf.erb
Only ensured on LetsEncrypt:
https://github.com/miraheze/puppet/blob/2228d4514b26c9821571d24fd1d547e8e60ed132/modules/letsencrypt/manifests/init.pp#L14-L21
=> mediawiki: remove acme-challenge

modules/icingaweb2/files/icinga2.conf, modules/roundcubemail/files/mail.miraheze.org.conf, modules/roundcubemail/files/roundcubemail.conf
Only ensured on LetsEncrypt:
https://github.com/miraheze/puppet/blob/2228d4514b26c9821571d24fd1d547e8e60ed132/modules/letsencrypt/manifests/init.pp#L14-L21
=> Remove acme-challenge from roundcubemail and icingaweb2

modules/varnish/templates/mediawiki.conf
This is per discussion in the Miraheze meeting yesterday for [T9213](https://phabricator.miraheze.org/T9213), so that we can create a short URL from miraheze.wiki/br to redirect to the Phabricator bug report form, so we can link the short URL in the exception message.
There are other uses for this as well though.
=> varnish: support redirecting paths in SSL redirects.yaml

modules/letsencrypt/files/ssl-certificate.py
This will prevent it from showing up in the script output
=> letsencrypt: suppress InsecureRequestWarning

modules/puppetdb/manifests/database.pp
`role::postgresql` is included in site.pp
=> puppetdb: remove `role::postgresql` and old debian versions

modules/users/data/data.yaml
Reverts miraheze/puppet#2605
Per the access policy, should be RSA or ed25519 keypair, reverting for now.
=> Revert "rhinosf1: add new key"

modules/monitoring/files/check_reverse_dns.py
We could probably use `sys.tracebacklimit`, but doing it this way, formatting it just seemed nicer.
=> check_reverse_dns: format exceptions, suppressing tracebacks

modules/varnish/templates/mediawiki.conf
Should only be merged with miraheze/ssl#541, at the same time.
=> varnish: always use case-insensitive redirects for `path_redirects`

modules/ssl/manifests/nginx.pp
Reverts miraheze/puppet#2688
Now we can remove this.
=> Revert "absent old letsencrypt nginx site"

modules/ssl/manifests/init.pp
This will ensure that everything in /home/ssl-admins has the correct permissions (writable by ssl-admins) and that /etc/puppetlabs/puppet/ssl-keys exists and has the correct permissions (writable by ssl-admins).
=> Manage /home/ssl-admins recursively + ensure existence and permissions for /etc/puppetlabs/puppet/ssl-keys

modules/nginx/templates/nginx.conf.erb
This value is increased in the debian package but the default value in generally is 1024.
=> nginx: set types_hash_max_size to 2048

modules/role/manifests/prometheus.pp
meta.miraheze.org main page is Miraheze not Main_Page.
=> prometheus: Use Miraheze rather then Main_Page

hieradata/hosts/mon141.yaml
When things get stuck it causes the load to sky rocket, lets lower this.
=> mon141: lower MaxConcurrentChecks to 40

hieradata/hosts/gluster101.yaml
Not needed to mount, we have it on all the mw*
=> gluster101: unmount /mnt/mediawiki-static

hieradata/common.yaml
With it low (at 20 seconds), 503s would be even more common, I think. So this reverts it back to 60 seconds now that gluster migration is done.
=> Raise varnish::interval-check to 60 seconds again

hieradata/common.yaml, modules/mediawiki/manifests/init.pp
The class is included via site instead.
=> Remove unused jobchron from hiera

modules/monitoring/files/users.conf
To update to full names as to match the [organisation](https://meta.miraheze.org/wiki/Tech:Organisation#Department:_Site_Reliability_Engineering) names, and since ssladmins and mediawiki does use an expanded full name, but for mediawiki just correct it to be "MediaWiki Engineers".
=> users: update display_name for sre and mediawiki

modules/nginx/templates/nginx-systemd-override.conf.erb
Matches what we have set in nginx.conf and also the default is based on the system which is 1024.
=> nginx: increase LimitNOFILE to 16192

modules/prometheus/templates/initscripts/prometheus-es-exporter.systemd_override.erb
I have applied changes (braedon/prometheus-es-exporter#59) locally to es131 in order to support this.
=> prometheus-es-exporter: use IPV6

modules/prometheus/templates/initscripts/prometheus-es-exporter.systemd_override.erb
Using this uses es131 (or whatever the elasticsearch master is), we don't need to define it with the server.
=> prometheus-es-exporter: use elasticsearch master only

modules/varnish/templates/stunnel.conf
This seems to successfully fix issues like:
```ps
2022.09.15 20:54:04 LOG3[317696]: s_connect: s_poll_wait 2a10:6740::6:403:443: TIMEOUTconnect exceeded
2022.09.15 20:54:04 LOG3[317696]: No more addresses to connect
```
=> stunnel: always listen through ipv6

hieradata/hosts/mw121.yaml, hieradata/hosts/mw122.yaml, hieradata/hosts/mw131.yaml, hieradata/hosts/mw132.yaml, hieradata/hosts/mw141.yaml, hieradata/hosts/mw142.yaml
using 32 is OOm'g, lets go to a smaller number.
=> mediawiki: reduce mediawiki::php::fpm::fpm_min_child to 20

modules/role/manifests/varnish.pp
This disables `net.ipv4.tcp_slow_start_after_idle` and sets `net.ipv4.tcp_notsent_lowat`
=> varnish: add some more network tuning

modules/base/files/apt/50unattended-upgrades
It seems `Unattended-Upgrade::MailOnlyOnError` is legacy, and deprecated on Debian Bullseye. Replace it with `Unattended-Upgrade::MailReport`
=> unattended-upgrades: replace MailOnlyOnError with MailReport

modules/varnish/templates/default.vcl
`2a10:6740::6/64` is what it should be here if I am not mistaken.
=> varnish: fix address (should be `::6`)

modules/swift/manifests/ac.pp, modules/swift/manifests/storage.pp
We don't want replication, we have to set a value to 1 or higher for replication in the rings but we don't have the disk space.
=> swift: mask service swift-*-replicator

hieradata/hosts/swiftobject111.yaml, hieradata/hosts/swiftobject112.yaml, hieradata/hosts/swiftobject113.yaml, hieradata/hosts/swiftobject114.yaml, hieradata/hosts/swiftobject115.yaml
Whilst I'm not too sure which number would be best, I've seen Wikimedia set this to 12 for some of their servers which is a better starting off place. We can lower / increase this depending how things work when production traffic starts flowing in as then we'll have the data.
=> swiftobject111/2/3/4/5: increase swift::storage::object_server_default_workers to 12

modules/monitoring/files/services.conf
Also changes ns1, since icinga indicates it isn't that high, we don't need it that high here. Additionally, removes ns1 from ping4, since it is not ever checking ping4 as only address6 is used when defining hosts.
=> Set higher ping threshold for cp32/cp33

modules/varnish/manifests/init.pp, modules/varnish/templates/initscripts/varnish.systemd.erb
According to the documentation [0], malloc is unlimited in varnish.
We change this to be dynamically set. Based on 2g on cp21/22/32/33, we'd set this to 1G.
[0] https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html
=> varnish: dynamically set malloc based on the ram available

modules/swift/manifests/ac.pp, modules/swift/manifests/storage.pp
With the replication set at one it means that there won't be copies, but we need this service to delete tombstones otherwise we'll run out of inodes.
=> swift: re enable swift*replicator

modules/monitoring/manifests/nrpe.pp
Drop the s as the number is in seconds, it does not need the s.
=> monitoring: fix nrpe_timeout

modules/monitoring/files/hosts.conf, modules/monitoring/files/services.conf
Also removes the `ping4` CheckCommand, and IPv4 address attribute from `ssh` since this was the only one using IPv4 address for monitoring.
=> Use IPv6 address for sslhost

modules/mediawiki/templates/mediawiki.conf.erb
This is served using the root container in swift.
=> mediawiki: fix favicon for static-new

modules/swift/templates/account-server.conf.erb, modules/swift/templates/container-server.conf.erb, modules/swift/templates/object-server.conf.erb
We don't want to wait 7 days for swift to delete accounts/objects/containers on the disk.
=> swift: set reclaim_age to 6 hours

modules/mediawiki/templates/mediawiki-includes.conf.erb
Alias won't work with Swift.
Additional checks for private is no longer necessary here, since it is redirecting to the static subdomain, if access to it is denied there it would be denied, so a redirect even for private should be fine here.
=> mediawiki: update static alias to just rewrite

hieradata/hosts/swiftobject114.yaml
=> swiftobject114/5: reduce workers

modules/mediawiki/templates/mediawiki.conf.erb
So /donate.php also redirects to donate.miraheze.org. Currently the above regex matches donate.php, so this one does not. Move it above, and make it regex so that it also matches.
=> mediawiki-landing: include redirecting donate.php

modules/ssl/manifests/nginx.pp
We don't need it. We already load the certificate we need with ssl::wildcard.
=> ssl::nginx: stop loading ssl::hiera

modules/mariadb/files/mysql-server.logrotate.conf, modules/mariadb/manifests/config.pp
By default in the mariadb packaging it sets within the logrotate file to use mysqladm with --defaults-file set for debian.cnf. We fix this by removing this param.
=> mariadb: fix logrotate config

modules/role/manifests/varnish.pp
This is to try and help avoid a large performance spike because of the flushing out to disk.
=> varnish: flush vm more steadily

modules/mediawiki/templates/mediawiki.conf.erb
To normalise the default so that multiple versions aren't the exact same content.
=> mediawiki-landing: redirect `/en` to `/`

modules/varnish/manifests/init.pp
=> varnish: up the max threads to 5000 - still experimenting

modules/mariadb/templates/config/mw.cnf.erb
The config was deprecated and now shows:
> 2022-11-26 19:50:03 0 [Warning] 'innodb-stats-sample-pages' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
in the logs
=> mariadb: remove innodb_stats_sample_pages from config file

modules/mariadb/templates/config/mw.cnf.erb
In mariadb 10.5.7, the default value was changed from 75 to 90. Change this back to 75%.
=> mariadb: set innodb_max_dirty_pages_pct to 75%

modules/swift/files/swift.logrotate.conf, modules/swift/files/swift.rsyslog.conf, modules/swift/manifests/init.pp
From:
- https://github.com/wikimedia/puppet/blob/production/modules/swift/files/swift.logrotate.conf
- https://github.com/wikimedia/puppet/blob/production/modules/swift/files/swift.rsyslog.conf
=> swift: add rsyslog rules

modules/mediawiki/manifests/jobqueue/runner.pp
Seems to have been broken over a year ago with dbe96ca. Using `-number` works (before it was -19), but using a positive number, it has to define `-n` for `nice` to work. As now it just returns: `/usr/bin/nice: ‘15’: No such file or directory`
=> mediawiki: fix `updateExternalLinks.php` cron

modules/ssl/files/ssl-certificate.py
there will be pushes to the repo from elsewhere (auto-renewal, adding redirects etc)
=> ssl-certificate: git pull first before attempting to push the public key

modules/swift/files/SwiftMedia/miraheze/rewrite.py
This issue happened intermittently. Remove transfer encoding header.
=> swift: fix issues with chunked transfer in proxy

manifests/site.pp
These have since been removed, so this doesn't need to match them anymore.
=> site: remove swiftobject114 and swiftobject115

modules/php/manifests/fpm/pool.pp
We have discovered what caused the memory leaks and it wasn't php-fpm. Let's increase this by 50%.
=> php: increase max requests by 50%

modules/monitoring/manifests/init.pp
The file doesn't exist anyways.
=> monitoring: check_icinga_config doesn't take a param

modules/mediawiki/manifests/jobqueue/runner.pp
This was 0 before, which doesn't exist, so was made 1, this readjusts everything else for that.
=> Change `backups-mediawiki-xml` to 3, 6, 9, 12

modules/prometheus/files/es_exporter/20-nginx.cfg
This modifies the nginx metrics query to improve its accuracy and focus on relevant data. The query now uses the match_phrase query type instead of the match query type for the application_name field, to ensure that only documents with an exact match are returned. The query also includes a filter for a specific time range, to narrow the results to a specific period.
In addition, the query includes min_doc_count and size parameters in the terms aggregations, to limit the results to HTTP status codes that have at least 10 documents and a maximum of 5 values. This helps to eliminate noise and focus on significant trends.
Finally, the query includes a new range aggregation for the request time field, which allows us to group documents by request time ranges rather than individual request …
=> es_exporter: improve accuracy of nginx metrics query

modules/mariadb/templates/mariadb-systemd-override.conf.erb
We default to read only on start-up, there is no risk to data and it means wikis become available after an OOM much faster. It’s far better to have wikis read only than down.
=> MariaDB: always restart

modules/varnish/templates/default.vcl
This pull request sets Content-Disposition: attachment on requests at static.miraheze.org that contain ?download.
This is required by Extension:MultiMediaViewer in order to actually download the file: see https://phabricator.miraheze.org/T10285.
The code is from Gilles <gdubuc@wikimedia.org> (https://gerrit.wikimedia.org/r/c/operations/puppet/+/120617), I just ported it to Miraheze.
=> T10285: Set Content-Disposition header on static.miraheze.org requests containing ?download

modules/varnish/templates/default.vcl
This PR modifies the HTML shown on "Backend Fetch Failed" errors to use SRI when retrieving the Bootstrap CSS from jsdelivr. SubResource Integrity is a security measure to be used when retrieving content on CDNs to prevent a series of possible attacks. For an introduction on SRI, see https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.
The hash is a SHA-384 hash created by me using OpenSSL 3.0.7. I generated it from both the Bootstrap GitHub 4.6.0 release (https://github.com/twbs/bootstrap/releases/tag/v4.6.0) and the file offered for download by jsdelivr, both returning the same hash.
=> Use SRI when fetching Bootstrap CSS

modules/ssl/files/mirahezerenewssl.py
the filelock library generates debug level logging statements for every lock interaction. This may not seem like much, but every process waiting for the lock will attempt to acquire it every 0.05 seconds, meaning a log line will be generated for every process every 0.05 seconds. ssl-acme can take over 8 minutes to run in some cases (based on current puppet141 logs). This means that 450 processes (equivalent to the number of certs that need to be renewed) would generate over 300MB of logs in 8 minutes. This would seem to be the cause of T10458
=> mirahezerenewssl.py: raise logging level to info

modules/ssl/files/ssl-certificate.py
didn't actually cause issues, since if the key hadn't actually changed then nothing would actually happen
=> fix accidental setting new private key to true every time

modules/ssl/files/ssl-acme
this makes issues easier to debug, is no longer needed since the pushing is no longer done in this script
=> renewal - don't use -q

modules/monitoring/manifests/init.pp
manage_repo is deprecated and recommends using manage_repos.
=> monitoring: switch from using manage_repo to manage_repos param

modules/mediawiki/manifests/jobqueue/runner.pp
No need to run on test131, when wiki is set to betawiki, move the backups (and monitoring) up, so they are not on test131, and icinga does not alert `FILE_AGE CRITICAL: File not found - /var/log/mediawiki-xml-backup.log` for test131
=> Only run MediaWiki XML backups on mwtask141, not test131 also

.github/pythonchecks.txt, .github/workflows/workflow.yml, modules/mediawiki/files/bin/deploy-mediawiki.py
Check python 3.11 instead to match likely next debian version
=> python: upgrade CI, support bookworm

modules/varnish/templates/default.vcl
This should fix the NGINX error rate, and also avoid contacting the backends for static.miraheze.org, as no images will be returned anyway (https://phabricator.miraheze.org/T10717).
=> Return Varnish's default 200 response on all requests to static

modules/role/manifests/graylog.pp
For some reason migrating from graylog121 to 131 is causing issues with the index (migration).
https://github.com/Graylog2/graylog2-server/issues/12963
=> graylog: set ignore_migration_failures

modules/mediawiki/files/bin/deploy-mediawiki.py
betawiki has been replaced by metawikibeta in Betaheze. Replacing this will also fix https://phabricator.miraheze.org/T10715
=> betawiki -> metawikibeta in deploy-mediawiki

modules/mediawiki/files/bin/deploy-mediawiki.py
Removes the need for the majority of extension-list
=> deploy-mediawiki: use --extensions-dir for mergeMessageFileList.php

modules/users/data/data.yaml
mw-admins already have the ability to restart PHP and Nginx so this shouldn't be a huge escalation.
=> Allow mediawiki-admins to restart Nutcracker

modules/mariadb/templates/config/mw.cnf.erb
mysql should automatically handle error recovery. There's no sense making it read-only especially if we don't have a procedure in place to validate the database after it's started up.
The only use case I can think of for having read-only on startup is for doing maintenance where the server is expected to restart, but we don't want any changes after the restart.
=> mariadb remove read-only on startup

modules/base/manifests/upgrades.pp
the link target doesn't seem to exist on new servers, and /etc/cron.daily/apt seems to have been replaced with /etc/cron.daily/apt-compat (there may also be something in systemd that supersedes that)
=> remove /etc/cron.daily/apt

modules/mariadb/templates/config/mw.cnf.erb
We use SSDs so can set this to 0.
=> mariadb: innodb_flush_neighbors set to 0

modules/mariadb/templates/config/mw.cnf.erb
Increases definition cache size to 50k and open cache to 80k
=> mariadb: increase table cache size

modules/mariadb/templates/config/mw.cnf.erb
We fixed the open files limit so can now set table_open_cache to 50k. Which in conjunction with table_open_cache_instances will equal 800k. (50k x 8 x 2 = 800).
We will keep table_open_cache at 100k on the dbs as the open file limit hasn't been applied as it requires a restart of service.
https://dba.stackexchange.com/questions/283064/server-with-mariadb-sometimes-dies-under-high-load
=> mariadb: set table_open_cache to 50k

hieradata/common.yaml, hieradata/hosts/test131.yaml, modules/mediawiki/manifests/jobqueue/runner.pp
We don't want to run over all wikis as it'll conflict with it running on mwtask. We only want it to run on beta wikis, lets use the beta.json file for this.
=> mediawiki: fix running the cron on beta

modules/mariadb/templates/config/mw.cnf.erb, modules/mariadb/templates/mariadb-systemd-override.conf.erb
Definition cache is set to 75k (half).
We had originally set this to 500k but because it used a lot of ram, lets lower this.
=> mariadb: set open table cache to 150k

modules/mariadb/templates/config/mw.cnf.erb
Some wikis (larger ones) are hitting the limit and thus we need to increase it.
=> mariadb: increase innodb_ft_cache_size to 150MB

modules/base/templates/backups/miraheze-backup.py.erb
mydumper uses too much ram for us to use. Although this means dumping will be longer and will also mean file sizes are larger.
=> miraheze-backup: use mysqldump to backup

modules/varnish/templates/default.vcl
Changes made:
* Excludes all MF IPs.
* Excludes seemingly-authenticated requests (simple cookie check)
* MW rest.php and MW API, Wikidata: 1000/10s (100/s long term, with 1000 burst)
* All others (excludes static): 1000/50s (20/s long term, with 1000 burst)
=> varnish: overhaul rate limits

modules/varnish/templates/default.vcl
Seems to be causing logged out users to hit each other's rate limits somehow.
=> varnish: use X-Real-IP for all rate limit logic

modules/mariadb/files/mysql-server.logrotate.conf
See https://serverfault.com/questions/375004/logrotate-not-rotating-the-logs
=> mariadb: read my.cnf from /root/ in logrotate file

modules/prometheus/files/redis/jobQueueCollector.lua
Per https://grafana.wikimedia.org/d/CbmStnlGk/jobqueue-job?orgId=1&var-dc=eqiad%20prometheus%2Fk8s&var-job=parsoidCachePrewarm&from=now-12h&to=now for https://github.com/miraheze/mw-config/pull/5245
=> Monitor parsoid warming jobs

modules/graylog/manifests/allinone.pp, modules/graylog/manifests/server.pp, modules/java/manifests/init.pp, modules/users/manifests/groupmembers.pp, modules/users/manifests/hashgroup.pp, modules/users/manifests/hashuser.pp
It's deprecated and removed in newer stdlib versions
=> Stop using has_key function

modules/graylog/manifests/server.pp
=> graylog: Use data type to state config should be hash

modules/ferm/manifests/init.pp
All servers are on bullseye. No longer need this check.
=> ferm: remove os_version check

hieradata/hosts/mw131.yaml, hieradata/hosts/mw132.yaml, hieradata/hosts/mw133.yaml, hieradata/hosts/mw134.yaml, hieradata/hosts/mw141.yaml, hieradata/hosts/mw142.yaml, hieradata/hosts/mw143.yaml, modules/mediawiki/manifests/php.pp
We set this to half of php childs on mw*.
=> mediawiki: add option to override emergency_restart_threshold

modules/base/templates/backups/miraheze-backup.py.erb
This is to find out which db it fails on.
=> miraheze-backup: add some logs for backing up db

hieradata/hosts/cp32.yaml
This reverts commit 7f71521b4208baa65720c52cdf67e3e761f32782.
=> Revert "cp32/cp33 lower storage size to 45g (#3358)"

modules/base/manifests/puppet.pp
This is until a bookworm repo is available.
=> base::puppet: force the puppet repo to use bullseye

modules/base/manifests/packages.pp
This package isn't available under bookworm and we no longer use the functions from this package.
=> Stop installing ruby-safe-yaml

modules/varnish/files/varnish/reload-vcl.py
See https://github.com/varnishcache/varnish-cache/blob/957509b3ae179e60319e6b9cf49e190cb4bfecbe/doc/sphinx/whats-new/upgrading-6.2.rst#listing-vcls
=> reload-vcl: fix support for varnish 6.2+ in auto discard

modules/varnish/templates/initscripts/varnish.systemd.erb
We use reload-vcl and don't need varnishreload.
=> varnish: Remove duplicate ExecReload from systemd unit

modules/nginx/templates/nginx.conf.erb
Also remove use epoll as it'll use epoll by default.
=> nginx: turn off multi_accept

modules/ssl/manifests/all_certs.pp
Puppet is currently not creating the proper notify relationship between `/etc/ssl/localcerts` and `Service['nginx']`. I'm assuming this is because `defined(Service['nginx'])` is returning false for some reason (possibly evaluation order?). For now, we can always assume we can reach it, given that all_certs is always called inside an nginx definition file.
Maybe we need a requires?
=> all_certs.pp assume nginx service exists

modules/varnish/manifests/init.pp, modules/varnish/templates/default.vcl, modules/varnish/templates/initscripts/varnish.systemd.erb
* Removes query parameters so cache hit increases.
* Lowercases extensions to also increase cache hits.
* Pipes dump requests.
* Unset Cache-Control header.
* And more improvements!
Note: Some of this code is from Wikimedia puppet repo (https://github.com/wikimedia/operations-puppet/blob/4f7dcacd8fc378b15db131f0f79be26cbec9182a/modules/varnish/templates/upload-frontend.inc.vcl.erb)
=> varnish: Improve static.miraheze.org

modules/varnish/templates/default.vcl
Sometimes the name contains double hyphens next to px.
=> Fix thumb video generation

modules/varnish/templates/mediawiki.conf
Our bursts for static are too high for these rate limits to work effectively. Will work on other detection methods for now.
=> revert nginx rate-limits

modules/matomo/templates/config.ini.php.erb
We use a reverse-proxy (nginx) now for varnish -> backend tls. Without this config, a indefinite redirect happened.
=> matomo: Set assume_secure_protocol to 1

modules/varnish/templates/mediawiki.conf
We don't need duplicate stuff, mw* will have it if we need it.
Don't disable error log as that will be useful in case.
=> varnish: Disable writing to access logs in reverse proxy

modules/php/manifests/default_extensions.pp, modules/php/manifests/init.pp
json comes by default in core thus the .so is no longer available.
=> php: Don't install json on 8.2+

modules/varnish/templates/default.vcl
Archived thumbnails should not include this information
=> thumbnail generation: don't include timestamp of archived files

modules/mediawiki/manifests/init.pp
On bookworm we get with pip3:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.11/README.venv for more information.
```
=> mediawiki: use python3-internetarchive deb package on bookworm+

modules/mediawiki/files/bin/deploy-mediawiki.py
This is to speed up deploying.
git pull --recursive-submodule takes ages so when you know the repo is already up-to-date we can skip this step.
=> deploy-mediawiki: force use of --pull to update world

modules/mediawiki/files/bin/mwscript.py, modules/mediawiki/files/bin/test_mwscript.py
CHANGELOG
- Drops `--140`/`--use-runner` option (now default)
- adds `--no-runner` to switch to old behaviour
- added `syscheck` method
- `get_commands` can now return an int as well as CommandInfo. Result of get_commands can be passed to syscheck method which will pass int to sys.exit or return CommandInfo. Migration `X = get_commands(args)` becomes `X = syscheck(get_commands(args))`
Developer Notes:
- Added some extra tests
- `get_commands` no longer calls `sys.exit` at any point
=> [BREAKING CHANGE] mwscript: make run.php no longer experimental

modules/varnish/templates/default.vcl
It was having issues with filenames that had dashes at the start.
=> varnish: Temporarily disable some thumb logic

modules/role/manifests/swift.pp
This is because we use the http proxy in MediaWIki and thus need bastions to be allowed to talk to swift-lb.
=> swift: Allow bastion to connect to swift-lb

modules/role/manifests/mediawiki/mcrouter.pp
We don't currently have a situation where we have two dc's and need syncing. Lets remove this to prevent duplicate data.
=> mediawiki::mcrouter: don't replicate

modules/mediawiki/manifests/extensionsetup.pp
Should be in /w not in /w/vendor
=> mediawiki: fix running vendor_psysh_composer

modules/mediawiki/manifests/jobqueue/runner.pp
We now add links when a change is saved rather than having to rely on a maintenance script.
=> runner: purge rottenlinks cron

modules/mediawiki/templates/jobrunner-hi.json.erb
* Removes parsoidCachePrewarm, refreshLinks* from claimTTL and real.
* Adjust DataDumpGenerateJob time for real.
=> jobrunner-hi: tune real/time for jobs

modules/mediawiki/manifests/deploy.pp
=> mediawiki::deploy: install langcodes with --break-system-packages

modules/monitoring/manifests/init.pp
=> monitoring: don't use http proxy for mariadb apt

modules/base/templates/dns/recursor.conf.erb
* It appears that sometimes ipv4 addresses are used. This appears to happen only when query-local-address contains 0.0.0.0.
Fix this by only using ipv6 (::).
=> dns: fix recursor for ipv6 only hosts

modules/base/templates/dns/recursor.conf.erb
Uses ipv6 for outgoing queries otherwise it's disabled and only ipv4 is used.
=> dns: set query-local-address to ::

modules/mediawiki/templates/mediawiki.conf.erb
See https://stackoverflow.com/questions/56486489/nginx-caching-dns-look-ups-and-ignoring-my-resolver-settings
=> mediawiki: use a variable for swift-lb in nginx

modules/varnish/templates/default.vcl
This causes it to be unset on the first-non-match making it basically only work for the very first backend making things like mwdeploy always fail after the first backend
=> Don't unset X-Miraheze-Debug

modules/ssh/templates/sshd_config.erb
Reverts miraheze/puppet#3204
My key malfunctions with this no matter what I do. Maybe we can do this when we all have Yubikey Bio keys, but not now.
=> Revert "sshd: enforce use of PIN+Touch on FIDO SSH"

modules/irc/templates/relaybot/config-relaybot2.ini.erb
cvtbot has been shutdown for WT so channel no longer needed
=> relaybot: remove #wikitide-cvt-feed

modules/irc/templates/logbot/config.py
I previously tried this in #1757 and it was reverted in #1759 as only one made it not being able to join at all, but I realized why: if there is not a comma after a single-element tuple, Python will not recognize it as a tuple at all, amd thus the for loop that makes it connect to IRC channels does nothing. So I want to see if this works. If it doesn't, we can revert again.
```py
targets = ("#miraheze-sre",)
print(type(targets))
<class 'tuple'>
targets = ("#miraheze-sre")
print(type(targets))
<class 'str'>
```
=> MirahezeLogbot: Don't join #miraheze-sre-security

modules/monitoring/manifests/init.pp, modules/role/files/graylog/logging.wikitide.net.conf, modules/role/manifests/graylog.pp, modules/role/manifests/prometheus.pp
Internal services can match hostnames on wikitide.net, which is the purpose of that domain to not have internal stuff on miraheze.org much.
=> graylog: use logging.wikitide.net

modules/grafana/files/nginx/grafana.conf, modules/grafana/manifests/init.pp, modules/grafana/templates/grafana.ini.erb, modules/varnish/templates/default.vcl
Internal services can match hostnames on wikitide.net, which is the purpose of that domain to not have internal stuff on miraheze.org much.
=> grafana: use grafana.wikitide.net

hieradata/hosts/mwtask171.yaml, hieradata/hosts/mwtask181.yaml, hieradata/hosts/test151.yaml, modules/httpd/manifests/init.pp
So that it does not conflict with nginx
=> jobrunner: remove default ports from apache2

modules/grafana/templates/ldap.toml.erb, modules/icingaweb2/templates/resources.ini.erb, modules/matomo/templates/config.ini.php.erb, modules/role/manifests/openldap.pp
Internal services can match hostnames on wikitide.net, which is the purpose of that domain to not have internal stuff on miraheze.org much.
=> ldap: use ldap.wikitide.net

hieradata/hosts/graylog161.yaml, modules/prometheus/templates/initscripts/prometheus-es-exporter.systemd_override.erb, modules/role/manifests/opensearch.pp, modules/role/templates/opensearch/nginx.conf.erb
Internal services can match hostnames on wikitide.net, which is the purpose of that domain to not have internal stuff on miraheze.org much.
=> opensearch: use opensearch.wikitide.net

modules/nginx/templates/nginx.conf.erb
Per "[warn] 684#684: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:21"
=> nginx: replace http2_max_field_size with large_client_header_buffers

modules/users/data/data.yaml
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
This commit adds a new key for my shell account at WikiTide. It is also an ed25519-sk key, created with a newly purchased YubiKey. It is meant as a backup in case my main key breaks.
This commit message, as well as the commit itself, is signed with my OpenPGP key.
-----BEGIN PGP SIGNATURE-----
iHUEARYKAB0WIQQK+0J/GAD9iXUcQDUpIihzWucH/wUCZip0vgAKCRApIihzWucH
/wN4AQCEV5+hVEhNempO6+LHAOdJhcSoUeVJY9ua4Ntnjyme3wD/YtI+iVCIeX83
1SYvSTXAtd07EgQGxHvlftB/chk3gQ8=
=tx1s
-----END PGP SIGNATURE-----
=> Add backup SSH key for myself

modules/users/data/data.yaml
Needed to make renames and recreations safely by making a backup of the db prior to performing the rename/recreation.
=> Allow dbadmins to use mysqldump

README.md
We no longer run Bullseye in our infra
=> Swap mentions of Debian Bullseye with mentions of Debian Bookworm

modules/base/manifests/init.pp
On Debian Bookworm, the ntp package is no longer the classic NTP daemon, but rather just a package that pulls in ntpsec as a dependency
This is a bit of a problem because https://github.com/puppetlabs/puppetlabs-ntp, the module we're using to manage ntp, is still built around classic NTP, and apparently Puppetlabs modules still only support as far as Debian Bullseye
This commit hacks that class enough for ntpsec support. Thankfully, we can use the generated config file still thanks to ntpsec keeping mostly the same config syntax and options
restrict has been modified according to the recommended values at https://github.com/ntpsec/ntpsec/blob/250d5896b053be5498c73b12e29a3c8b07aaf11a/etc/ntp.d/use-no-remote-configuration
=> hack the ntp class for ntpsec compatibility

modules/base/templates/backups/wikitide-backup.py.erb
database source was renamed to sql
add support for there being more than 10000 objects in the container
=> wikitide-backup update find_backups

modules/irc/manifests/pywikibot.pp
On Bookworm python3-pillow is a virtual package (https://packages.debian.org/bookworm/python3-pillow)
The only package providing that is python3-pil. This makes it so that Puppet doesn't try again and again to install python3-pillow on every run
=> pywikibot: ensure python3-pil is installed instead

modules/irc/manifests/pywikibot.pp
Only the irc user should ever need to read this file anyway, and there's no reason to edit it outside of puppet
=> pywikibot: make user-config read-only for the irc user

modules/irc/manifests/pywikibot.pp
the irc user doesn't have permissions to just create files in /var/log, but we can solve this by just giving it its own directory at /var/log
=> pywikibot: write logs to the /var/log/pwb dir

modules/irc/manifests/pywikibot.pp, modules/irc/templates/pywikibot/pywikibot.sh
https://issue-tracker.miraheze.org/T12244
This commit prepares for the migration from git to an install managed by the archive module. It moves config files outside of the install directory of pywikibot, and introduces a wrapper script that runs pywikibot with the correct env vars set so that it is able to still find the family and user-config files
=> T12244: pywikibot: Move config files to /var/local/, introduce pywikibot wrapper script

modules/irc/manifests/pywikibot.pp
This commit prevents puppet from touching the mode of files in $install_path.
Some files in the git repository of pywikibot have the executable bit set, making them 755. If Puppet changes the mode of these files to 644, the Git::clone puppet manifest will not pull new changes due to there being local changes in the repository (https://issue-tracker.miraheze.org/T12244#245049).
=> pywikibot: do not recursively apply mode 644 on $install_path

modules/mediawiki/data/csp.yaml
```
> dig sumin.wiki | grep HEADER
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 30368
> dig wiki-assets.sumin.wiki | grep HEADER
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 658
> whois sumin.wiki | head
No Data Found
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2024-07-14T06:56:02Z <<<
For more information on Whois status codes, please visit https://icann.org/epp
The Service is provided so that you may look up certain information in relation to domain names that we store in our database.
Use of the Service is subject to our policies, in particular you should familiarise yourself with our Acceptable Use Policy and our Privacy Policy.
```
=> Remove dead domain from CSP

modules/mediawiki/templates/mediawiki.conf.erb
This will allow us to blow up the CF mediawiki cache without also blowing up static.mh.o
This might help the usual broken caches after the MW upgrade.
=> add Cache-Tag to mediawiki responses

modules/mediawiki/manifests/packages.pp
Needed for the Phonos extension
https://issue-tracker.miraheze.org/T11704
=> T11704: Install espeak and LAME on the MediaWiki appservers

modules/mediawiki/templates/mediawiki.conf.erb
Also a test for if we can have both of the client certificate directives together
=> T12554: Trust the internal client certificate on mirabeta.org

modules/mediawiki/files/bin/mwdeploy.py, modules/mediawiki/manifests/deploy.pp, modules/mediawiki/templates/mediawiki.conf.erb
https://issue-tracker.miraheze.org/T12554#251242
The perms are kind of bad for the private key, but this particular client certificate only allows making requests to mw*
It also needs to be accessed by the user running mwdeploy, setting mw-admins, for example, as the owner group would prevent ops from using mwdeploy
=> Trust the internal client certificate CA as well

modules/nginx/templates/nginx.conf.erb
This is similar to wikimedias config https://github.com/wikimedia/operations-puppet/blob/4f4c75d518edf5121802eca475e20800f0fcc5c8/modules/profile/templates/tlsproxy/nginx.conf.erb#L77
=> nginx: set ssl_session_tickets to off

hieradata/hosts/changeprop151.yaml, modules/eventgate/files/config.yaml
Also update job concurrency numbers. We don't want a situation where the server is overloaded. So lets lower this substantially and increase only when resources show it can.
=> changeprop/eventgate: Change config to point at prod

modules/role/manifests/kafka.pp
Uses G1 for GC. Increasing performance.
=> kafka: set jvm options

modules/mediawiki/templates/mediawiki-includes.conf.erb
this sets fastcgi_intercept_errors on; which means that error responses within php-fpm are passed to nginx for error handling rather than directly to the end user.
we define another location block for /ErrorPages so that php based error pages will work correctly.
this was done going by https://stackoverflow.com/questions/23106349/nginx-pass-all-404-errors-back-to-php-fpm-for-custom-error-page-processing
=> mediawiki: nginx: allow passing of php-fpm error responses to nginx for handling via custom ErrorPages

modules/base/templates/backups/wikitide-backup.py.erb
We want it to log when systemd timer runs.
https://unix.stackexchange.com/questions/285419/systemd-python-service-not-sending-all-output-to-syslog#comment497256_285419
=> wikitide-backup: run script with -u

hieradata/hosts/db161.yaml
The database is not on db161, it's on db171.
=> db161: Remove mhglobal from weekly backup

hieradata/hosts/db151.yaml
The database is not on db151, it's on db171.
=> db151: Remove mhglobal from weekly backup

modules/base/templates/backups/wikitide-backup.py.erb
We have smaller machines so lets make this more lenient.
We run 6 cores for the dbs but we may have to change this if we increase this further
=> wikitide-backup: Instead of doing <cores>/8 do it over 3

hieradata/hosts/db181.yaml
The database is not on db181, it's on db171.
=> db181: Remove mhglobal from weekly backup

modules/nginx/manifests/init.pp
Change it to less then 2gb not less then 90 (I mistakenly thought it was something else but now realise).
=> nginx: fix setting ssl_session_cache for machines with more ram

modules/base/templates/backups/wikitide-backup.py.erb
Means we know if an error occurred and no ioerror happened.
=> wikitide-backup: add except to pca_connection

modules/mediawiki/manifests/jobqueue/runner.pp
The documentation says you only need to run this once on wiki install. Wikimedia don't run this periodic either.
=> mediawiki::jobqueue::runner: disable clean_gu_cache cron

modules/mediawiki/manifests/jobqueue/runner.pp
The documentation says you only need to run this once.
=> mediawiki::jobqueue::runner: remove clean_gu_cache cron

modules/mediawiki/manifests/jobqueue/runner.pp
These have been purged so can now be removed.
=> mediawiki::jobqueue::runner: remove old cron jobs

modules/ssl/manifests/wildcard.pp, modules/varnish/templates/mediawiki.conf.erb
This is the final thing that still uses the now expired section cert. This also removes the cert definition for the old cert from the SSL module.
=> switch cp* default ssl to CF origin cert

modules/mediawiki/data/csp.yaml
=> T12091: Add {games,economy}.roblox.com to the correct CSP directive

modules/base/templates/backups/wikitide-backup.py.erb
We run it locally on the host so we don't need to compress. We already compress when it outputs.
=> wikitide-backup: Don't run mysqldump with -C

modules/base/templates/backups/wikitide-backup.py.erb
> Use complete INSERT statements that include column names.
=> wikitide-backup: Set -c for sql backup

hieradata/role/common/mediawiki.yaml, hieradata/role/common/mediawiki_beta.yaml, hieradata/role/common/mediawiki_task.yaml, modules/mediawiki/manifests/php.pp
* Use a multiplier instead of manually defining the php childs. We multiple by 2 so (12 * 2).
* We use total cores for emergency restart threshold. We no longer manually define it.
=> mediawiki: update php-fpm config

modules/mediawiki/manifests/init.pp, modules/mediawiki/manifests/jobqueue/runner.pp
* Only run it where mediawiki::jobqueue::runner::cron is set to true
=> mediawiki: move backup-all-wikis-ia cron to jobrunner class

modules/swift/manifests/proxy.pp
Ensure the cert that is being served isn't going to expire.
=> swift::proxy: Add nginx ssl check

modules/mediawiki/templates/mediawiki.conf.erb, modules/nginx/templates/nginx.conf.erb, modules/role/templates/bastion/mediawiki.conf.erb, modules/varnish/templates/mediawiki.conf.erb
Also switch reverse proxies that use https:// to use tls v1.3. Solution found with https://unix.stackexchange.com/questions/706074/nginx-reverse-proxy-fails-with-tlsv1-3-on-backend-servers.
=> nginx: use TLS v1.3

hieradata/role/common/mediawiki_task.yaml
Use the default that we set which is 500M.
We override based on usage inside MW anyways.
=> mediawiki_task: unset memory_limit

modules/mediawiki/manifests/php.pp
I thought it already did that but appears not. Also removed memory_limit config. You can override it in fpm_config. No need for a separate config.
=> mediawiki: Set memory_limit to default to 500M

modules/mariadb/templates/config/mw.cnf.erb
=> mariadb: default to read_only on startup

modules/role/manifests/cloud.pp
For maintenance when both bastions are temporarily down we will need to do this temporarily. Not to be merged until just before maintenance and reverted afterwards.
=> Temp allow cloud ssh without bastion

modules/changeprop/manifests/init.pp
libssl1.1 is not available on bookworm. Instead use libssl-dev which will install what ever newer version is available.
=> changeprop: install libssl-dev

modules/mediawiki/manifests/jobqueue/runner.pp
It's causing issues internally.
=> mediawiki::jobqueue::runer: remove managewikis systemd timer for now

modules/salt/files/bin/upgrade-packages.sh, modules/salt/manifests/init.pp
To puppetize, we've always had it on puppet181 but better to actually puppetize the script.
=> Add upgrade-packages script

hieradata/hosts/changeprop201.yaml
Copys https://github.com/wikimedia/operations-deployment-charts/commit/c9f95e06ecfee40833837a5925aca2af8c1e36f9
=> changeprop201: increase max.poll.interval.ms to 2h for webVideoTranscode

modules/role/templates/cache/haproxy/tls_terminator.cfg.erb
Seems to interfere with grafana? I don't think this is needed or is what fixed the issue with random wiki requests ending up at grafana.
=> cache::haproxy: remove option http-server-close from the varnish backends

hieradata/role/common/cache/cache.yaml
Also corrects what header to look at for debug.
=> cache::haproxy: Remove X-OpenStack-Request-ID header if X-Wikitide-Debug isn't present

modules/mediawiki/templates/mediawiki-includes.conf.erb, modules/mediawiki/templates/mediawiki.conf.erb
Reading up, this is recommended for large uploads? And it's similar behaviour to apache which has less ability to configure behaviour with fastcgi.
=> mediawiki: set fastcgi_request_buffering to off

modules/role/templates/cache/haproxy.cfg.erb
We need a larger value so logs aren't truncated.
=> cache::haproxy: set tune.http.logurilen for logs logged locally

hieradata/role/common/cache/cache.yaml
Issues with file uploads that take ages to upload or hit the timeout. To fix this, it seemed increasing this to 1mb improved the sitation so you weren't waiting too long. Experiment was done with a 40m file.
=> cache::haproxy: set initial_window_size to 1048576

modules/role/templates/cache/haproxy/tls_terminator.cfg.erb
Cloudflare I think sets this header? And nonetheless we set it in varnish.
=> cache::haproxy: unset forwardfor

modules/monitoring/templates/ssl.conf.erb
No certificates are expected to require automatic renewal between now and May 16th when our Hosted DNS service is due to close. Therefore, these can be let to expire as all certs by then will be managed by Cloudflare.
=> ssl: switch off automatic cert renewal for custom domains

modules/opensearch/README.md, modules/opensearch/REFERENCE.md, modules/opensearch/lib/puppet/provider/opensearch_component_template/ruby.rb, modules/opensearch/lib/puppet/provider/opensearch_index_template/ruby.rb, modules/opensearch/lib/puppet/type/opensearch_component_template.rb, modules/opensearch/lib/puppet/type/opensearch_index_template.rb, modules/opensearch/manifests/component_template.pp, modules/opensearch/manifests/index_template.pp, modules/opensearch/manifests/init.pp
This copies [0] but modifies it for opensearch.
[0] https://github.com/voxpupuli/puppet-elasticsearch/commit/37cda0c1ac602492088770a7553df5e712818f47
=> Add support for composable index templates

modules/base/templates/dns/resolv.conf.erb
So that they can better access our internal network
=> resolver: use our own ns servers for query lookups

modules/matomo/templates/config.ini.php.erb
We don't use the plugin, it's not installed and you have to pay for it.
=> matomo: remove CustomReports

modules/matomo/manifests/init.pp
Trying to fix:
> /srv/matomo/core/CliMulti.php(484): Warning - filemtime(): stat failed for /srv/matomo/tmp/climulti/archive.sharedsiteids.pid
=> matomo: Set --concurrent-archivers to 3

modules/base/templates/dns/recursor.conf.erb, modules/base/templates/dns/resolv.conf.erb
This should allow local networking (like to fsslc.wtnet) to resolve locally rather than failing and then forwarding to ns1.
=> Fix recursor if forward_use_internal

modules/mediawiki/templates/mediawiki.conf.erb
We will use versioned file names, when CSS is changed filenames will change to recache the new version. This allows for much longer cache expiry and overall better performance.
=> Use long, immutable cache for css files on landing

modules/role/templates/cache/haproxy/tls_terminator.cfg.erb
This is to fix sometimes the wrong request ending up at the wrong backend.
=> cache::haproxy: Set http-reuse to never for frontend and use keepalive for varnish -> haproxy

hieradata/role/common/mediawiki.yaml, hieradata/role/common/mediawiki_task.yaml
We set opcache to 8gb so 3% of that is 245mb.
=> mediawiki: set opcache.max_wasted_percentage to 3%

modules/role/manifests/cache/varnish.pp
It won't work with how we have it setup (needs nginx) and we're behind cloudflare now.
=> role::cache::varnish: Stop using fail2ban
